### PR TITLE
[KYUUBI #2643][FOLLOWUP] Using javax AuthenticationException instead of hadoop AuthenticationException

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

Using javax.security.sasl.AuthenticationException instead of hadoop AuthenticationException
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
> The UserGroupInformation may also be replaced by jdk Subject?
Seems difficult to do that if user use `UserGroupInformation.setLoginUser(loginUser)`.

**Comment by ulysses-you** [comment]
seems we can remove hadoop dependency in pom ?

**Comment by turboFei** [comment]
> seems we can remove hadoop dependency in pom ?

It is still used here.
https://github.com/apache/incubator-kyuubi/pull/2787/files#diff-282b1e8c3fee6a8b8b6814d201ba42ad60fc1a1b5546fcc2a31150f3e5ff89abR46

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by turboFei** [comment]
thanks for your review @ulysses-you

**Pull request closed without merging**
