### PR TITLE
[KYUUBI #1958] Fix flaky test: statement redact for engine tab 

### LINKED ISSUE #1958: Flaky test: statement redact for engine tab *** FAILED ***
```
- statement redact for engine tab *** FAILED ***
  "<!DOCTYPE html><html>
        <head>
          <meta http-equiv="Content-type" content="text/html; charset=utf-8"/><link rel="stylesheet" href="/static/bootstrap.min.css" type="text/css"/><link rel="stylesheet" href="/static/vis-timeline-graph2d.min.css" type="text/css"/><link rel="stylesheet" href="/static/webui.css" type="text/css"/><link rel="stylesheet" href="/static/timeline-view.css" type="text/css"/><script src="/static/sorttable.js"></script><script src="/static/jquery-3.4.1.min.js"></script><script src="/static/vis-timeline-graph2d.min.js"></script><script src="/static/bootstrap-tooltip.js"></script><script src="/static/initialize-tooltips.js"></script><script src="/static/table.js"></script><script src="/static/timeline-view.js"></script><script src="/static/log-view.js"></script><script src="/static/webui.js"></script><script>setUIRoot('')</script>
          <script>setAppBasePath('')</script>
          
          
          <link rel="shortcut icon" href="/static/spark-logo-77x50px-hd.png"></link>
          <title>kyuubi_runner_spark_2022-02-22T06:17:53.627939Z - Kyuubi Query Engine</title>
        </head>
        <body>
          <div class="navbar navbar-static-top">
            <div class="navbar-inner">
              <div class="brand">
                <a href="/" class="brand">
                  <img src="/static/spark-logo-77x50px-hd.png"/>
                  <span class="version">3.0.3</span>
                </a>
              </div>
              <p class="navbar-text pull-right">
                <strong title="kyuubi_runner_spark_2022-02-22T06:17:53.627939Z">kyuubi_runner_spark_2022-02-22T0...</strong> application UI
              </p>
              <ul class="nav"><li class="">
          <a href="/jobs/">Jobs</a>
        </li><li class="">
          <a href="/stages/">Stages</a>
        </li><li class="">
          <a href="/storage/">Storage</a>
        </li><li class="">
          <a href="/environment/">Environment</a>
        </li><li class="">
          <a href="/executors/">Executors</a>
        </li><li class="">
          <a href="/SQL/">SQL</a>
        </li><li class="active">
          <a href="/kyuubi/">Kyuubi Query Engine</a>
        </li></ul>
            </div>
          </div>
          <div class="container-fluid">
            <div class="row-fluid">
              <div class="span12">
                <h3 style="vertical-align: bottom; display: inline-block;">
                  Kyuubi Query Engine
                  
                </h3>
                <a href="/kyuubi/?&sessionstat.sort=Finish+Time&sessionstat.pageSize=100#sessionstat">
                  <span data-toggle="tooltip" data-placement="top" title="">
                    Finish Time
                  </span>
                </a>
              </th><th>
                <a href="/kyuubi/?&sessionstat.sort=Duration&sessionstat.pageSize=100#sessionstat">
                  <span data-toggle="tooltip" data-placement="top" title="">
                    Duration
                  </span>
                </a>
              </th><th>
                <a href="/kyuubi/?&sessionstat.sort=Total+Statements&sessionstat.pageSize=100#sessionstat">
                  <span data-toggle="tooltip" data-placement="top" title="">
                    Total Statements
                  </span>
                </a>
              </th></tr>
      </thead>
            <tbody>
              <tr>
          <td> runner </td>
          <td> 127.0.0.1 </td>
          <td> 127.0.0.1 </td>
          <td> <a href="/kyuubi/session/?id=49f331da-796a-4fb2-[826](https://github.com/apache/incubator-kyuubi/runs/5283822512?check_suite_focus=true#step:5:826)9-299cc4f03742"> 49f331da-796a-4fb2-8269-299cc4f03742 </a> </td>
          <td> 2022/02/22 06:18:07 </td>
          <td> 2022/02/22 06:18:11 </td>
          <td> 4 seconds 27 ms </td>
          <td> 1 </td>
        </tr>
            </tbody>
          </table>
          <div>
        <div>
          <form id="form-sessionstat-bottom-page" method="get" action="/kyuubi/?&sessionstat.sort=Start+Time&sessionstat.desc=true#sessionstat" class="form-inline pull-right" style="margin-bottom: 0px;">
            <input type="hidden" name="sessionstat.sort" value="Start Time"/><input type="hidden" name="sessionstat.desc" value="true"/>
            <label>1 Pages. Jump to</label>
            <input type="text" name="sessionstat.page" id="form-sessionstat-bottom-page-no" value="1" class="span1"/>
            <label>. Show </label>
            <input type="text" id="form-sessionstat-bottom-page-size" name="sessionstat.pageSize" value="100" class="span1"/>
            <label>items in a page.</label>
  
            <button type="submit" class="btn">Go</button>
          </form>
        </div>
        <div class="pagination" style="margin-bottom: 0px;">
          <span style="float: left; padding-top: 4px; padding-right: 4px;">Page: </span>
          <ul>
            
            
            <li class="disabled"><a href="#">1</a></li>
            
            
          </ul>
        </div>
      </div>
        </div>
          </div><span id="sqlstat" class="collapse-aggregated-sqlstat collapse-table" onClick="collapseTable('collapse-aggregated-sqlstat',
                  'aggregated-sqlstat')">
          <h4>
            <span class="collapse-table-arrow arrow-open"></span>
            <a>SQL Statistics (0)</a>
          </h4>
        </span><div class="aggregated-sqlstat collapsible-table">
            No statistics have been generated yet.
          </div>
          </div>
        </body>
      </html>" did not contain "0 session(s) are online," (EngineTabSuite.scala:161)
```

### PR DESCRIPTION
**Pull request by wForget**
### _Why are the changes needed?_

close #1958 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
can we use connection share level  instead ?

**Comment by wForget** [comment]
> can we use connection share level instead ?

We may not, this is to start KyuubiSparkEngine directly, not submitted through KyuubiServer.

**Comment by ulysses-you** [comment]
I think they are same, we also use jdbc to do test at engine side. Can see an example `ConnectionLevelSparkEngineSuite`.

**Comment by wForget** [comment]
> I think they are same, we also use jdbc to do test at engine side. Can see an example `ConnectionLevelSparkEngineSuite`.

@ulysses-you  got it, but we probably don't need a connection-level engine, can we just make `EngineTabSuite` extends `WithDiscoverySparkSQLEngine`?

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
seems it's trivial

thanks, merging to master

**Pull request closed without merging**
