### PR TITLE
[1.5] Revert "[KYUUBI #1948] Upgrade thrift version to 0.16.0"

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

This PR reverts "[KYUUBI #1948] Upgrade thrift version to 0.16.0" in branch-1.5 and some subsequent commits due to issues caused by breaking changes in Thrift, e.g. #2101, #2093

We need more time to evaluate it and add more test cases to ensure stability before the next release. 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by ulysses-you — APPROVED** [review]

**Review by cfmcgrady — APPROVED** [review]

**Comment by pan3793** [comment]
Seems we don't need the following confs, THRIFT-4805 only affects thrift 0.12
```
# SPARK-34128: Suppress undesirable TTransportException warnings, due to THRIFT-4805
appender.console.filter.1.b.type = RegexFilter
appender.console.filter.1.b.regex = .*Thrift error occurred during processing of message.*
appender.console.filter.1.b.onMatch = deny
appender.console.filter.1.b.onMismatch = neutral
```

**Comment by pan3793** [comment]
Seems we don't need the following confs, THRIFT-4805 only affects thrift 0.12 @yaooqinn 
```
# SPARK-34128: Suppress undesirable TTransportException warnings, due to THRIFT-4805
appender.console.filter.1.b.type = RegexFilter
appender.console.filter.1.b.regex = .*Thrift error occurred during processing of message.*
appender.console.filter.1.b.onMatch = deny
appender.console.filter.1.b.onMismatch = neutral
```

**Comment by yaooqinn** [comment]
we need them, we don't shade them after reverting

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to 1.5

**Comment by pan3793** [comment]
Also merged to master because there is no workaround for https://github.com/apache/incubator-kyuubi/issues/2101#issuecomment-1064820187 now

**Pull request closed without merging**
