### PR TITLE
[KYUUBI #2028] Hive Backend Engine - Events support

### PR DESCRIPTION
**Pull request by zhaomin1423**
### _Why are the changes needed?_

Add events support for hive engine.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
Hi @zhaomin1423 can we wait a bit for #1853

**Comment by yaooqinn** [comment]
https://github.com/apache/incubator-kyuubi/pull/1853 is merged, can you rebase master?

**Comment by zhaomin1423** [comment]
> #1853 is merged, can you rebase master?

Thanks， I will update it.

**Comment by yaooqinn** [comment]
thanks, merged to master

**Pull request closed without merging**
