### PR TITLE
[KYUUBI #2631] Rename high availability config key to support multi discovery client

### PR DESCRIPTION
**Pull request by hddong**
### _Why are the changes needed?_

Rename high availability config key to support muti discovery client

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by hddong** [comment]
cc @yaooqinn @pan3793 
changes:
`kyuubi.ha.zookeeper.namespace` -> `kyuubi.ha.discovery.deploy.namespace`
`kyuubi.ha.zookeeper.quorum` -> `kyuubi.ha.discovery.endpoints`
`kyuubi.ha.service.discovery.client.class` -> `kyuubi.ha.discovery.client.class`

**Comment by yaooqinn** [comment]
kyuubi.ha.zookeeper.namespace -> kyuubi.ha.namespace
kyuubi.ha.zookeeper.quorum -> kyuubi.ha.endpoints
kyuubi.ha.service.discovery.client.class -> kyuubi.ha.client.class

**Comment by pan3793** [comment]
WDYT the following style?
```
kyuubi.ha.type=<zookeeper|etcd|custom>

kyuubi.ha.zookeeper.k1=
kyuubi.ha.zookeeper.k2=
kyuubi.ha.etcd.k1=
kyuubi.ha.etcd.k2=
kyuubi.ha.custom.class=
kyuubi.ha.custom.k1=
kyuubi.ha.custom.k2=
```

**Comment by hddong** [comment]
> kyuubi.ha.zookeeper.namespace -> kyuubi.ha.namespace
> kyuubi.ha.zookeeper.quorum -> kyuubi.ha.addresses
>kyuubi.ha.service.discovery.client.class -> kyuubi.ha.client.class

Changed

>`kyuubi.ha.type=<zookeeper|etcd|custom>

This change had put in the next PR(supoort etcd) and will push resently, we can unify the name of some common configs first.

**Comment by yaooqinn** [comment]
is kyuubi.ha.type duplicated with kyuubi.ha.client.class?

**Comment by hddong** [comment]
> is kyuubi.ha.type duplicated with kyuubi.ha.client.class?

It wil used when type is custom, and be option

**Comment by yaooqinn** [comment]
> > is kyuubi.ha.type duplicated with kyuubi.ha.client.class?
> 
> It will be used when type is custom, and be option

if the class is provided, why do we need an extra type to specify it?

**Comment by hddong** [comment]
> if the class is provided, why do we need an extra type to specify it?

IMO, in project ,we always use type to choice built in classes (such as: auth, evnets). 
https://github.com/apache/incubator-kyuubi/blob/33c816240d3c1eee744bad351c5ae25c54f64139/kyuubi-server/src/main/scala/org/apache/kyuubi/server/KyuubiServer.scala#L56-L59
And in `KyuubiServer`, we need `create chroot path if necessary` when ues `ZK`. `ha.type` match may better than `client.class` equals to check if discovery client is zk.

**Comment by yaooqinn** [comment]
> > if the class is provided, why do we need an extra type to specify it?
> 
> IMO, in project ,we always use type to choice built in classes (such as: auth, evnets).
> 
> https://github.com/apache/incubator-kyuubi/blob/33c816240d3c1eee744bad351c5ae25c54f64139/kyuubi-server/src/main/scala/org/apache/kyuubi/server/KyuubiServer.scala#L56-L59
> 
> 
> And in `KyuubiServer`, we need `create chroot path if necessary` when ues `ZK`. `ha.type` match may better than `client.class` equals to check if discovery client is zk.

the code path your provide, I don't know very well
but the client.class is duplicated with type

**Comment by hddong** [comment]
> the code path your provide, I don't know very well but the client.class is duplicated with type

How about
```
kyuubi.ha. type=<zk|etcd|custom>
kyuubi.ha.custom.class=Optional[String]
```

**Comment by yaooqinn** [comment]
why is zk so special?

**Comment by yaooqinn** [comment]
check the code in kyuubi server again, it looks like it can be removed(it's a quite rare and odd case) or share with all discovery clients

**Comment by hddong** [comment]
> check the code in kyuubi server again, it looks like it can be removed(it's a quite rare and odd case) or share with all discovery clients

Ok, will remove it when support etcd.

**Comment by yaooqinn** [comment]
less is more, I prefer to remain less configurations

**Comment by hddong** [comment]
> less is more, I prefer to remain less configurations

Had revert it.
now:
```scala
kyuubi.ha.namespace
kyuubi.ha.addresses
kyuubi.ha.client.class
```

**Review by yaooqinn — APPROVED** [review]

**Comment by hddong** [comment]
@yaooqinn @pan3793 thanks for review, merging to master

**Pull request closed without merging**
