### PR TITLE
[KYUUBI #956] Fail to get table list if there is _ in schema's name

### PR DESCRIPTION
**Pull request by Baoqi**
Just write some basic tests out in other projects. 

Since this toJavaRegex is not a static function, which is hard to write unit test if don't move it out as  as static function in object.  (But in that case, the change may be too large for this).

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
can we add a test then for `if there is _ in schema's name` ?

**Comment by yaooqinn** [comment]
we can add an end to end test for this case，it’s very easy to use the current test framework

**Comment by yaooqinn** [comment]
also cc @pan3793 as the release manager of 1.3.0

**Comment by Baoqi** [comment]
> can we add a test then for `if there is _ in schema's name` ?

Sure, after some check, it seems the best place to add this test is in "get schemas" of BasicJDBCTests.scala.

it will be included in the following 5 final test suites:
  - KyuubiOperationHiveCatalogSuite
  - KyuubiOperationPerServerSuite
  - KyuubiOperationPerUserSuite
  - KyuubiStatementMonitorSuite
  - SparkOperationSuite

Without my fix, but with my unit test change,   the first 3 suite still success, but the last 2 will fail.  (haven't got time to learn what is different between first 3 suites with the last 2 suites)

After my fix, for the new unit test change,  all 5 suites will success.

**Comment by pan3793** [comment]
The changes LGTM, but may I know where the original implementations come from?

**Comment by Baoqi** [comment]
> The changes LGTM, but may I know where the original implementations come from?

Hi, as in the comments of source code:

      * (referred to Spark's implementation: convertPattern function in file MetadataOperation.java)

**Comment by pan3793** [comment]
> > can we add a test then for `if there is _ in schema's name` ?
> 
> Sure, after some check, it seems the best place to add this test is in "get schemas" of BasicJDBCTests.scala.
> 
> it will be included in the following 5 final test suites:
> 
> * KyuubiOperationHiveCatalogSuite
> * KyuubiOperationPerServerSuite
> * KyuubiOperationPerUserSuite
> * KyuubiStatementMonitorSuite
> * SparkOperationSuite
> 
> Without my fix, but with my unit test change, the first 3 suite still success, but the last 2 will fail. (haven't got time to learn what is different between first 3 suites with the last 2 suites)
> 
> After my fix, for the new unit test change, all 5 suites will success.

The first 3 suites are `jdbc-client` ==> `kyuubi-spark-engine`.
The later 2 suites are `jdbc-client` ==> `kyuubi-server` ==> `kyuubi-spark-engine`.

Seems somethings happens in `kyuubi-server` when passing through the request, like remove escape chars.

**Comment by pan3793** [comment]
> > The changes LGTM, but may I know where the original implementations come from?
> 
> Hi, as in the comments of source code:
> 
> ```
>   * (referred to Spark's implementation: convertPattern function in file MetadataOperation.java)
> ```
> 
> see https://github.com/apache/spark/blob/master/sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/operation/MetadataOperation.java#L103
> 
> only the 3 lines are likely same with Spark's implementation.
> 
> Since Kyuubi is based on Spark, and both projects belongs to Apache Foundation, so, I assume this is fine. But please let me know if we need a modified version. Thanks.

Yea, I see, what I mean **original implementations** is the existing code before this PR. Have a quick look on Hive codebase, didn't find the clue. @yaooqinn Do you remember that?

**Review by pan3793 — APPROVED** [review]
LGTM

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master and 1.3

**Pull request closed without merging**
