### PR TITLE
[DOCS] Fix typo

### PR DESCRIPTION
**Pull request by legendtkl**
### Change
Minor change

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master

**Comment by pan3793** [comment]
@legendtkl Have you link your email taokelu@bytedance.com to GitHub account? Otherwise, your contribution is not accounted.

**Comment by legendtkl** [comment]
> @legendtkl Have you link your email [taokelu@bytedance.com](mailto:taokelu@bytedance.com) to GitHub account? Otherwise, your contribution is not accounted.

Thanks for the remind, @pan3793 . I have rewritten the commit with the recorded email.

**Comment by pan3793** [comment]
The original commit has been merged into master branch, we can not change the commit history, one GitHub account can be associated w/ multi emails, you can just link a new email w/o replacing the existing one.

**Pull request closed without merging**
