### PR TITLE
[SUB-TASK][KPIP-1] Register default ObjectMapper instead of manually serialize/deserialize JSON input argument.

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

Register default `ObjectMapper` instead of manually serialize/deserialize JSON input argument.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by cfmcgrady** [comment]
cc @yanghua @yaooqinn

**Comment by yanghua** [comment]
@cfmcgrady Thanks, LGTM. BTW, can you refactor it thoroughly? IMO, after changing the return value of the request method, we may also remove the code like `OBJECT_MAPPER.readValue` . WDYT?

**Comment by cfmcgrady** [comment]
> @cfmcgrady Thanks, LGTM. BTW, can you refactor it thoroughly? IMO, after changing the return value of the request method, we may also remove the code like `OBJECT_MAPPER.readValue` . WDYT?

SGTM, updated.

**Comment by ulysses-you** [comment]
@cfmcgrady the change LGTM, but I think the change is not minor. Can we also collect the PR to https://github.com/apache/incubator-kyuubi/issues/950 ?

**Comment by cfmcgrady** [comment]
> @cfmcgrady the change LGTM, but I think the change is not minor. Can we also collect the PR to #950 ?

It seems to I don't have edit issue permission, need @yanghua's help to add to the task list.

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by yanghua** [comment]
> > @cfmcgrady the change LGTM, but I think the change is not minor. Can we also collect the PR to #950 ?
> 
> It seems to I don't have edit issue permission, need @yanghua's help to add to the task list.

sure.

**Comment by cfmcgrady** [comment]
Thanks for the review.

**Pull request closed without merging**
