### PR TITLE
Handles configuring the JUL -> SLF4J bridge

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

Handles configuring the JUL -> SLF4J bridge, otherwise, the components which use JUL like Jersey will be not controlled by log4j2 configurations

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
thanks, I will have a integration testing.

**Comment by turboFei** [comment]
please also remove the dependency in 
extensions/spark/kyuubi-spark-authz/pom.xml

**Review by cxzl25 — APPROVED** [review]

**Review by turboFei — APPROVED** [review]
Have made integration testing, it works well

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
