### PR TITLE
[KYUUBI #940] Fix process-logger-capture thread consumes high usage CPU

### PR DESCRIPTION
**Pull request by timothy65535**
### _Why are the changes needed?_

After several benchmarks in the offline environment, kyuubi consumes a lot of CPU.

```
[bigdata]$ jps
3188 Main
6036 Jps
4189 KyuubiServer

[bigdata]$ top
top - 09:34:21 up 23 min,  1 user,  load average: 10.67, 7.85, 4.98
Tasks: 320 total,   1 running, 319 sleeping,   0 stopped,   0 zombie
%Cpu(s): 48.2 us, 23.9 sy,  0.0 ni, 27.4 id,  0.0 wa,  0.5 hi,  0.0 si,  0.0 st
MiB Mem :  15806.0 total,   4738.4 free,   6085.0 used,   4982.5 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   9306.5 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                      
   4189 bigdata   20   0   10.1g 311272  22484 S 633.3   1.9  48:12.21 java      
```
```
Threads:  53 total,   6 running,  47 sleeping,   0 stopped,   0 zombie
%Cpu(s): 31.9 us, 22.8 sy,  0.0 ni, 44.8 id,  0.0 wa,  0.4 hi,  0.0 si,  0.0 st
MiB Mem :  15806.0 total,   4770.5 free,   6052.9 used,   4982.5 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   9338.7 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                      
   5222 bigdata   20   0   10.1g 311272  22484 R  99.3   1.9  10:00.91 process-logger-                              
   5044 bigdata   20   0   10.1g 311272  22484 R  99.0   1.9  10:03.98 process-logger-                              
   4730 bigdata   20   0   10.1g 311272  22484 R  98.3   1.9  10:13.24 process-logger-                              
   4911 bigdata   20   0   10.1g 311272  22484 R  98.3   1.9  10:06.42 process-logger-                              
   4523 bigdata   20   0   10.1g 311272  22484 R  98.0   1.9  10:41.55 process-logger-                              
   5769 bigdata   20   0   10.1g 311272  22484 R  96.7   1.9   2:46.80 process-logger- 
```

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
Can you package with this PR to confirm if it's effective to reduce the cpu load.

**Comment by timothy65535** [comment]
> Can you package with this PR to confirm if it's effective to reduce the cpu load.

Yeah, has been confirmed offline.

**Review by yaooqinn — APPROVED** [review]
LGTM, if @ulysses-you's comment is satisfied

**Comment by yaooqinn** [comment]
> > Can you package with this PR to confirm if it's effective to reduce the cpu load.
> 
> Yeah, has been confirmed offline.

please attached the result after this patched in the PR description

**Comment by timothy65535** [comment]
> > > Can you package with this PR to confirm if it's effective to reduce the cpu load.
> > 
> > 
> > Yeah, has been confirmed offline.
> 
> please attached the result after this patched in the PR description

Got, just wait a while, check it again.

**Comment by timothy65535** [comment]
@yaooqinn @ulysses-you here is the result, the cpu usage is lower.

```
[bigdata]$ jps
21968 Jps
21264 SparkSubmit
21138 SparkSubmit
21602 SparkSubmit
21436 SparkSubmit
20744 KyuubiServer

[bigdata]$ top -p 20744
top - 16:32:18 up  7:21,  1 user,  load average: 7.79, 6.64, 3.62
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s): 14.0 us,  1.1 sy,  0.0 ni, 84.4 id,  0.0 wa,  0.6 hi,  0.0 si,  0.0 st
MiB Mem :  15806.0 total,    350.0 free,  11429.1 used,   4026.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   3932.1 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                      
  20744 bigdata   20   0    9.9g 190208  22864 S   0.0   1.2   0:08.74 java                                         
```

**Comment by timothy65535** [comment]
In old codebase, the `process-logger-capture` will never be interrupted, because `reader.readLine()` does not catch InterruptedException.

image

**Comment by ulysses-you** [comment]
thank you @timothy65535 , merging to master/v1.3.0

**Comment by yaooqinn** [comment]
thanks for the fix！

**Pull request closed without merging**
