### PR TITLE
avoid NPE in KyuubiHiveDriver.acceptsURL

### PR DESCRIPTION
**Pull request by gabrywu**
### _Why are the changes needed?_

avoid NPE in KyuubiHiveDriver.acceptsURL

### _How was this patch tested?_

- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Thanks @gabrywu, are you interested in https://github.com/apache/incubator-kyuubi/issues/2492?

**Review by pan3793 — APPROVED** [review]

**Comment by gabrywu** [comment]
> Thanks @gabrywu, are you interested in #2492?

Don't know its purpose, can you give more details?

**Comment by pan3793** [comment]
The `kyuubi-hive-jdbc` is based on `hive-jdbc` module of Apache Hive branch-2.3, we copied, changed(fix bugs or add new features), and shaded(cut down transitive dependencies) it.
Now we want to rebuild this module based on Hive branch-3.1 because branch-3.1 contains more bug fixes and features.

**Comment by pan3793** [comment]
Thanks, merging to master

**Comment by gabrywu** [comment]
> The `kyuubi-hive-jdbc` is based on `hive-jdbc` module of Apache Hive branch-2.3, we copied, changed(fix bugs or add new features), and shaded(cut down transitive dependencies) it. Now we want to rebuild this module based on Hive branch-3.1 because branch-3.1 contains more bug fixes and features.

I can try, need time to conduct investigations.

**Pull request closed without merging**
