### PR TITLE
[KYUUBI 770] Fix flaky test: Add config to control if cancel invoke interrupt task on engine

### PR DESCRIPTION
**Pull request by timothy65535**
### _Why are the changes needed?_

Fix flaky test: Add config to control if cancel invoke interrupt task on engine.

```
The code passed to eventually never returned normally. Attempted 1783 times over 30.01599386 seconds. Last failure message: 0 did not equal 1.
ScalaTestFailureLocation: org.apache.kyuubi.engine.spark.SparkEngineSuites at (IndividualSparkSuite.scala:62)
```

**ROOT CAUSE**

When the operating system is under pressure at a certain point in time and the `forceCancel` is true.
The statement `assert(System.currentTimeMillis() - taskEnd.taskInfo.launchTime < 3000)` will throw Exception, it
cause the following statement can not be executed. 

```
override def onTaskEnd(taskEnd: SparkListenerTaskEnd): Unit = {
  assert(taskEnd.reason.isInstanceOf[TaskKilled])
  if (forceCancel.get()) {
    assert(System.currentTimeMillis() - taskEnd.taskInfo.launchTime < 3000)
    index.incrementAndGet()
  } else {
    assert(System.currentTimeMillis() - taskEnd.taskInfo.launchTime >= 4000)
    index.incrementAndGet()
  }
}
```

### _How was this patch tested?_
- [X] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @ulysses-you

**Comment by yaooqinn** [comment]
#783 merged, please trigger ci again thanks

**Comment by ulysses-you** [comment]
hi @timothy65535 the change LGTM, please rebase on latest master to trigger test

**Comment by timothy65535** [comment]
Thanks @yaooqinn @ulysses-you

**Review by yaooqinn — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]

**Pull request merged**
