### PR TITLE
[KYUUBI #1889] Improve the user experience of the configuration parameters of the document

### PR DESCRIPTION
**Pull request by cxzl25**
### _Why are the changes needed?_
https://kyuubi.apache.org/docs/latest/deployment/settings.html
The configuration parameters in the document are too long and a newline is inserted(`<br/>`), which makes it difficult to search.
And if the user copies the configuration parameters, it may become several lines.

Use `<code>` to replace `<br/>`.

https://github.com/apache/incubator-kyuubi/issues/1889

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by cxzl25** [comment]
## current
image


## fix
image

**Comment by pan3793** [comment]
Could you please give a full-page screenshot?

**Comment by pan3793** [comment]
I remember there are other places in `docs/` also use `<br/>`, please also change them to make the doc consistent

**Review by yaooqinn — APPROVED** [review]

**Comment by cxzl25** [comment]
Now I increased the max-width of the content to avoid the horizontal scrollbar.

image

**Comment by cxzl25** [comment]
> I remember there are other places in `docs/` also use `<br/>`, please also change them to make the doc consistent

After looking for it, I only saw the metrics.md file, which is a table written by hand, and it was also modified.

image

**Review by hddong — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
great improvement ! merging to master

**Pull request closed without merging**
