### PR TITLE
Compatible with the Microsoft Active Directory LDAP

### PR DESCRIPTION
**Pull request by jetliu1711**
### _Why are the changes needed?_

Currently, Apache Kyuubi support open LDAP, cannot support Microsoft Active Directory LDAP,I try much more times, So
I try to debug LdapAuthenticationProviderImpl class,I find something wrong with use  Active Directory LDAP to connect to kyuubi authorized.it can be connect ,but close connect have something wrong,so I clear the close method,it can be very well。support Active Directory LDAP。

This pr aims to modify the documentation to indicate that version 2.4 is not supported

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Hi @jetliu1711, thanks for investigating, could you please open PR for master branch?

**Comment by pan3793** [comment]
Merge master to branch-1.6 does not make sense, close this PR to save CI resource.

**Comment by jetliu1711** [comment]
> Merge master to branch-1.6 does not make sense, close this PR to save CI resource.
 sorry,my operator mistake,I want to marge to master。

**Comment by yaooqinn** [comment]
image

it seems not the target branch is wrong, but the source branch is wrong, you should use the one in your fork.

**Comment by pan3793** [comment]
Please make sure you choose the right repo/branch for pull request, e.g. merge `pan3793`/`tpcds-doc` to `apache`/`master`

image

**Comment by jetliu1711** [comment]
> Please make sure you choose the right repo/branch for pull request, e.g. merge `pan3793`/`tpcds-doc` to `apache`/`master`
> 
> image

ok

**Comment by jetliu1711** [comment]
> image
> 
> it seems not the target branch is wrong, but the source branch is wrong, you should use the one in your fork.

thanks

**Pull request closed without merging**
