### PR TITLE
[KYUBBI #2142][DOCS] Add IDEA setup guide

### PR DESCRIPTION
**Pull request by deadwind4**
### _Why are the changes needed?_

Add IDEA setup guide for developers.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks for add this guide. BTW, Kyuubi also use Google Java Format tool for Java code, could you please add it?

**Comment by deadwind4** [comment]
> Thanks for adding this guide. BTW, Kyuubi also uses Google Java Format tool for Java code, could you please add it?

What version is the Google Java Format tool that I add it? As Flink code style, all Flink developers must set v1.7.0.6 version.

**Comment by pan3793** [comment]
I don't know if we can use the specific version of plugin in IDEA.
https://github.com/apache/incubator-kyuubi/blob/07d363204a52a0969bd3e32a2da131d18d3ee78d/pom.xml#L1685-L1718

**Comment by deadwind4** [comment]
I add java code formatting in this PR. We can choose v1.7.0.6.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks @deadwind4!
We also provided a shell script `dev/reformat`, would you like to send a new PR for that?

**Comment by deadwind4** [comment]
> Thanks @deadwind4! We also provide a shell script `dev/reformat`, would you like to send a new PR for that?

I can add how to use `dev/reformat` in `developer.md` in a new PR.

**Comment by pan3793** [comment]
Thanks, merging to master.

**Pull request closed without merging**
