### PR TITLE
[TEST] Add log if pod status is unexpected

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

Help debug failed test.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @zwangsheng @cfmcgrady @yaooqinn

**Review by cfmcgrady — APPROVED** [review]

**Comment by zwangsheng** [comment]
Can you show what the log can tells us through screenshots or log fragments?

**Review by yaooqinn — APPROVED** [review]

**Comment by ulysses-you** [comment]
@zwangsheng it depends on the exception type, with no image error we can get such exception:
```
Message: container "kyuubi-server" in pod "kyuubi-test" is waiting to start: trying and failing to pull image. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=container "kyuubi-server" in pod "kyuubi-test" is waiting to start: trying and failing to pull image, 
```

**Comment by ulysses-you** [comment]
thanks, merging to master

**Pull request closed without merging**
