### PR TITLE
Sync contents for CONTRIBUTING & COMMUNITY between web and main repo 

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

Add CONTRIBUTING.md to list COMMUNITY resources that I contributor can use
delete contributions and improvement-proposal in main repo

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by SteNicholas** [comment]
@yaooqinn, could you please add the introduction of the `dev/reformat` and `build/dependency.sh` in the contribution guide?

**Comment by yaooqinn** [comment]
> @yaooqinn, could you please add the introduction of the `dev/reformat` and `build/dependency.sh` in the contribution guide?

these will be added in docs dev tools and then added here as a list later

**Comment by ulysses-you** [comment]
> could you please add the introduction of the dev/reformat and build/dependency.sh in the contribution guide?

yes, it is really helpful. And maybe should include more, e.g. generate config docs if change config.

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Pull request closed without merging**
