### PR TITLE
[INFRA][DOCS] Improve release template script

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

Add $prev_release_version to generate change log link.
e.g. 
https://github.com/apache/incubator-kyuubi/compare/v1.5.1-incubating...v1.5.2-incubating-rc0

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
@yaooqinn @pan3793 @turboFei

**Comment by yaooqinn** [comment]
> 4. Generate change log for the release and send a pr to master branch

this is wrong. you can not use master branch for voting

**Comment by ulysses-you** [comment]
It's a good point.. but the change log required the tag exists, seems the pipeline can be ?

1. create tag for the release candidate at local
2. generate the change log
3. delete the tag at local
4. push the change log to the release branch
5. create tag for the release candidate

**Comment by yaooqinn** [comment]
It's annoying...

**Review by yaooqinn — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Pull request closed without merging**
