### PR TITLE
Add v1.5.2-incubating changelog

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

Add v1.5.2-incubating changelog for release

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @yaooqinn @pan3793

**Comment by ulysses-you** [comment]
wait for a blocker issue https://github.com/apache/incubator-kyuubi/pull/2848

**Comment by ulysses-you** [comment]
since it's not a blocker, merging to master

**Comment by yaooqinn** [comment]
yea, but it still has a chance to get in 1.5.2 during RC

**Pull request closed without merging**
