### PR TITLE
[KYUUBI #2047] Support more MySQL JDBC driver versions

### PR DESCRIPTION
**Pull request by cxzl25**
### _Why are the changes needed?_
Support more MySQL JDBC driver versions.
The user may use the 5.x mysql driver to connect to the kyuubi server.

https://github.com/apache/incubator-kyuubi/issues/2047

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]
The current approach is fragile, it should be replaced by antlr based SQL parser eventually.

**Comment by cxzl25** [comment]
[mysql_init_select.sql.txt](https://github.com/apache/incubator-kyuubi/files/8192825/mysql_init_select.sql.txt)


Grab the initialization sql of mysql-connector-java version from 5.1.20 to 8.0.28, and get the parameter list after deduplication.

```
@@auto_increment_increment
@@character_set_client
@@character_set_connection
@@character_set_results
@@character_set_server
@@collation_connection
@@collation_server
@@have_query_cache
@@init_connect
@@interactive_timeout
@@license
@@lower_case_table_names
@@max_allowed_packet
@@net_buffer_length
@@net_write_timeout
@@performance_schema
@@query_cache_size
@@query_cache_type
@@sql_mode
@@system_time_zone
@@time_zone
@@transaction_isolation
@@tx_isolation
@@wait_timeout
```

**Comment by cxzl25** [comment]
> The current approach is fragile, it should be replaced by antlr based SQL parser eventually.

Yes, I tried to use the mysql protocol on Friday and encountered this problem, and I also considered whether to consider introducing antlr.

**Comment by pan3793** [comment]
Kyuubi will introduce Antlr eventually, we have a prototype discussion previously, we'd like to introduce some Kyuubi defined SQL-like grammer, e.g. `SHOW ENGINES [LIKE ...]`, `ALTER SESSION SET ...`, it's something like [ShardingSphere DistSQL](https://github.com/apache/shardingsphere/releases)

**Comment by cxzl25** [comment]
> Kyuubi will introduce Antlr eventually, we have a prototype discussion previously, we'd like to introduce some Kyuubi defined SQL-like grammer, e.g. `SHOW ENGINES [LIKE ...]`, `ALTER SESSION SET ...`, it's something like [ShardingSphere DistSQL](https://github.com/apache/shardingsphere/releases)

Make sense. 
May be I missed the previous discussion.

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
> May be I missed the previous discussion.

Sorry, it happened in offline discussion.

Don't hesitate if you think we need to introduce antlr deps, even now we don't have detail design of the Kyuubi dialect  SQL grammar, but I need some intuitive commands like `SHOW ENGINES`, `SHOW SESSIONS`, and we also need to implement a basic single table `SELECT ... FROM ... WHERE ... LIMIT ... OFFSET ...` for MySQL.

**Comment by cxzl25** [comment]
> Could not find artifact org.apache.kyuubi:kyuubi-XXX_2.12:jar:1.6.0-SNAPSHOT in apache.snapshots

apache snapshot does not have deploy 1.6 version, causing UT to fail.

https://repository.apache.org/content/groups/snapshots/org/apache/kyuubi/

**Comment by cxzl25** [comment]
> Don't hesitate if you think we need to introduce antlr deps, even now we don't have detail design of the Kyuubi dialect SQL grammar, but I'm sure we need some intuitive commands like `SHOW ENGINES`, `SHOW SESSIONS`, and we also need to implement a basic single table `SELECT ... FROM ... WHERE ... LIMIT ... OFFSET ...` for MySQL.

ok, I will continue to pay attention to the development of the kyuubi project and see what I can do, thanks.

**Review by ulysses-you — APPROVED** [review]

**Review by SteNicholas — APPROVED** [review]
LGTM.

**Comment by pan3793** [comment]
Thanks, merging to master/1.5

**Pull request closed without merging**
