### PR TITLE
[KYUUBI #3581][Authz] Support Row Filter and Data Masking on Permanent Views

### LINKED ISSUE #3581: [FEATURE] [Authz] support row filter and data masking on permanent views
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

support row filter and data masking on permanent views.

### Motivation

_No response_

### Describe the solution

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

to close #3581 .

support row filter and data masking on permanent views,
1. matching permanent views with `PermanentViewMarker` injected by `RuleApplyPermanentViewMarker`
2. reusing attributes's exprId in new Alias for permanent views for data masking

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
only reusing attributes's `exprId` in new `Alias` for permanent views.
Otherwise, `KYUUBI #2390: RuleEliminateMarker stays in analyze phase for data masking` unit test will fail on querying table with column data masking with exception 
```
java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.Alias cannot be cast to org.apache.spark.sql.catalyst.expressions.Attribute
  at org.apache.spark.sql.catalyst.expressions.AttributeMap.get(AttributeMap.scala:37)
  at scala.collection.MapLike.apply(MapLike.scala:143)
  at scala.collection.MapLike.apply$(MapLike.scala:143)
  at org.apache.spark.sql.catalyst.expressions.AttributeMap.apply(AttributeMap.scala:37)
  at scala.collection.immutable.List.map(List.scala:297)
  at org.apache.spark.sql.hive.execution.HiveTableScanExec.<init>(HiveTableScanExec.scala:77)
```

**Comment by yaooqinn** [comment]
can you take a look at the test failures

**Comment by bowenliang123** [comment]
OK, all CI tests passed and it should be ready for merge. @yaooqinn

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
LGTM, I will merge it later. I hit `Exceeded the GitHub API rate limit` right now.

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by bowenliang123** [comment]
ps. Thanks to @yaooqinn for the concrete and helpful suggestions of solving `Ailas` id conflict in data masking in this PR.

**Pull request closed without merging**
