### PR TITLE
[KYUUBI #3805][FOLLOWUP] Skipping PySpark tests for nightly build

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

correct the wrong PySpark tag setting, and make it take effect for `spark-master` only.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by cfmcgrady** [comment]
cc @pan3793 @bowenliang123

**Comment by bowenliang123** [comment]
`PySparkTest` is still left in global setting , what you think whether we should keep this? @cfmcgrady 
https://github.com/apache/incubator-kyuubi/blob/master/pom.xml#L221

**Review by bowenliang123 — APPROVED** [review]

**Comment by cfmcgrady** [comment]
> `PySparkTest` is still left in global setting , what you think whether we should keep this? @cfmcgrady https://github.com/apache/incubator-kyuubi/blob/master/pom.xml#L221

it should take effect for `spark-master` only

**Comment by bowenliang123** [comment]
LGTM.
Thanks for the fix. And sorry for my mistakes in last PRs of https://github.com/apache/incubator-kyuubi/pull/3846 and https://github.com/apache/incubator-kyuubi/pull/3832 which failed to correct the whole problem.

**Review by pan3793 — APPROVED** [review]

**Pull request closed without merging**
