### PR TITLE
[TEST] Fix Flink flaky test - select count

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

Fix the flaky test

```
- execute statement - select count *** FAILED ***
  92 did not equal 100 (FlinkOperationSuite.scala:663)
```

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
changes expected or bug? and do you have any chance to elaborate about the reason?

**Comment by pan3793** [comment]
cc @SteNicholas @link3280 could you please confirm if the change makes sense or not?

**Comment by link3280** [comment]
I think this could be a temporary fix if it causes instability in tests. But I can't reproduce the issue, the test runs fine on my machine.

I had a glance at the git history and found that this test is for validating changes to table statistics. IMHO, row counts from table metadata should be only used for query optimization, not for the actual result set, thus I'm thinking if the assert is necessary at the beginning (or we just wanna ensure the statement runs).

Pulling in the author @liaoyt for his opinion.

**Review by SteNicholas — APPROVED** [review]
LGTM.

**Comment by pan3793** [comment]
cc @deadwind4

**Comment by cxzl25** [comment]
I tried adding multiple loops to this ut, and I can indeed reproduce this problem.
But from the log, I found nothing unusual.

In addition, because `flink-runtime-1.15.2-tests.jar` contains `log4j2-test.properties`, `rootLogger.level = OFF` is set, the priority of `log4j-test2.xml` in kyuubi is lower than that of properties, it does not take effect, in the test of Flink some logs are missing, should we change the `log4j-test2.xml` of this flink module to `log4j2-test.properties`?

**Comment by pan3793** [comment]
we override the `<log4j2.configurationFile>src/test/resources/log4j2-test.xml</log4j2.configurationFile>` in `scalatest-maven-plugin`, you mean it does not take effect?

**Comment by cxzl25** [comment]
> we override the `<log4j2.configurationFile>src/test/resources/log4j2-test.xml</log4j2.configurationFile>` in `scalatest-maven-plugin`, you mean it does not take effect?

The flink test log downloaded from GA does have output logs.
Test with `./build/mvn test`, there are also output logs.

Maybe I use IDEA's scala test (org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner), so there is no `log4j2.configurationFile` configured with scalatest-maven-plugin, then no log output in debug mode.

**Comment by pan3793** [comment]
It's open for a long time, I'm going to merge it to fix the frequent test failures, although I don't know what happened under the hood.

Feel free to rework this test case if you have any ideas.

**Comment by yaooqinn** [comment]
> It's open for a long time, I'm going to merge it to fix the frequent test failures, although I don't know what happened under the hood.
> 
> Feel free to rework this test case if you have any ideas.

If this is not a complete solution, it might be better to add `// TODO` with your change. And an issue ticket is also recommended.

**Comment by pan3793** [comment]
Tracking in #3583

**Pull request closed without merging**
