### PR TITLE
[KYUUBI #1593] use user set host or ip instead of read hostname from user set

### PR DESCRIPTION
**Pull request by zwangsheng**
### _Why are the changes needed?_

User can select IP or hostname for binding.
Detail #1593 

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
we dont need a extra conf，we can respect user directly

**Comment by zwangsheng** [comment]
> we dont need a extra conf，we can respect user directly

Do you mean just use the string that the user set?

**Comment by yaooqinn** [comment]
> > we dont need a extra conf，we can respect user directly
> 
> Do you mean just use the string that the user set?

yes

**Review by yaooqinn — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master/branch-1.4

**Pull request closed without merging**
