### PR TITLE
[CI] Cross version verification for spark-3.3

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

Cross version verification for spark-3.3

### _How was this patch tested?_

Pass CI.

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
FYI: RC3 is created in few minutes ago

**Comment by yaooqinn** [comment]
maybe it is time for us to discuss deprecate 3.0

**Comment by ulysses-you** [comment]
+1 to deprecate spark 3.0.x

**Review by yaooqinn — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Pull request closed without merging**
