### PR TITLE
Flaky Test: KyuubiBatchYarnClusterSuite - open batch session

### LINKED ISSUE #2522: Flaky Test: KyuubiBatchYarnClusterSuite - open batch session
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
KyuubiBatchYarnClusterSuite:
- open batch session *** FAILED ***
  The code passed to eventually never returned normally. Attempted 207 times over 10.023100855000001 seconds. Last failure message: RUNNING did not equal ERROR. (KyuubiBatchYarnClusterSuite.scala:83)
```

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

To close #2522

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by yaooqinn** [comment]
Hi @turboFei @ulysses-you, any diagnosis provided? Increasing timeout blindly could solve the test flakiness, but also might suppress actual bugs

**Comment by turboFei** [comment]
> Hi @turboFei @ulysses-you, any diagnosis provided? Increasing timeout blindly could solve the test flakiness, but also might suppress actual bugs
checking.

Before, It only happened for jdk11 testing.

And I can not reproduce it, but it seems that it is not resolved now.

Looking into this.

**Comment by turboFei** [comment]
After think twice, I think the reason is might that, the application is running in yarn-client mode and the local process does not terminate quickly.

I can set `spark.submit.deployMode` to `cluster`.

**Pull request closed without merging**
