### PR TITLE
Creates the default zk address instead of falling back to frontend bind address

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

As the Spark driver may launch from another node, when we start the Kyuubi server with an embedded zookeeper and bind the frontend address to `0.0.0.0`, the backend engine can't register correctly.

This pr changes the default behavior of `kyuubi.zookeeper.embedded.client.port.address`, creates the default zookeeper address with local hostname instead of falling back to `kyuubi.frontend.bind.host`.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by cfmcgrady** [comment]
cc @ulysses-you @yaooqinn @pan3793

**Comment by yaooqinn** [comment]
can you take a look at the test failure？

**Comment by cfmcgrady** [comment]
> can you take a look at the test failure？

The `Check all kyuubi configs` failed. Due to the current documents check mechanism, we can't generate dynamic config at runtime (e.g. create a config entry with default value local hostname).
I will update later.

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master

**Pull request closed without merging**
