### PR TITLE
[KYUUBI #1439] Add KYUUBI_CTL_JAVA_OPTS to configure java opts of kyuubi-ctl.

### PR DESCRIPTION
**Pull request by wForget**
### _Why are the changes needed?_

Add KYUUBI_CTL_JAVA_OPTS to configure java opts of kyuubi-ctl. For details: #1439.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
- Check all kyuubi configs *** FAILED *** 

3000 java.lang.AssertionError: assertion failed: /home/runner/work/incubator-kyuubi/incubator-kyuubi/docs/deployment/settings.md out of date, please update doc with KYUUBI_UPDATE=1 build/mvn clean install -Pspark-provided -DwildcardSuites=org.apache.kyuubi.config.AllKyuubiConfiguration

**Review by yaooqinn — APPROVED** [review]

**Comment by wForget** [comment]
```
MySQLAuthPacketSuite:
- encode MySQLHandshakePacket *** FAILED ***
  UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 103, cap: 256) did not equal UnpooledHeapByteBuf(ridx: 0, widx: 103, cap: 103/103) (MySQLCodecHelper.scala:43)
- decode MySQLHandshakeResponse41Packet
- encode MySQLAuthSwitchRequestPacket
- decode MySQLAuthSwitchResponsePacket
```

@yaooqinn ,it doesn’t seem to be caused by this PR, can you recheck it?

**Comment by pan3793** [comment]
> ```
> MySQLAuthPacketSuite:
> - encode MySQLHandshakePacket *** FAILED ***
>   UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 103, cap: 256) did not equal UnpooledHeapByteBuf(ridx: 0, widx: 103, cap: 103/103) (MySQLCodecHelper.scala:43)
> - decode MySQLHandshakeResponse41Packet
> - encode MySQLAuthSwitchRequestPacket
> - decode MySQLAuthSwitchResponsePacket
> ```
> 
> @yaooqinn ,it doesn’t seem to be caused by this PR, can you recheck it?

Fixed in master by #1442, please rebase master

**Review by turboFei — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks merged to master and 1.4

**Pull request closed without merging**
