### PR TITLE
[KYUUBI#2333] Add JAVA_OPTS parameter to *-engine.sh to enable remote debugging

### LINKED ISSUE #2333: [Improvement] Add JAVA_OPTS parameter to *-engine.sh to enable remote debugging
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add JAVA_OPTS parameter to *-engine.sh to enable remote debugging

### How should we improve?

Add JAVA_OPTS parameter to *-engine.sh to enable remote debugging

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jiaoqingbo**
### _Why are the changes needed?_

fix #2333 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by jiaoqingbo** [comment]
> maybe you can create a pr for flink like #2336

ok I'll try to make it

**Comment by yaooqinn** [comment]
thanks @jiaoqingbo 

After https://github.com/apache/incubator-kyuubi/pull/2336 is also available for flink, I guess we can

introduce 
- [FLINK|TRINO|HIVE]_JAVA_OPTS
- [FLINK|TRINO|HIVE]_JAVA_MEMORY or kyuubi.engine.[flink/hive/trino].memory

to introduce java_opts for engine process in a consistent way

**Review by SteNicholas — CHANGES_REQUESTED** [review]
@jiaoqingbo, thanks for your contribution. I left the minor comments for Flink engine. PTAL.

**Comment by SteNicholas** [comment]
@jiaoqingbo, do you have any changes? In addtion, please resolve the conflicts.

**Comment by jiaoqingbo** [comment]
> @jiaoqingbo, do you have any changes? In addtion, please resolve the conflicts.

I'm working on this and will submit later。Thanks for your advice

**Comment by deadwind4** [comment]
Could you add a section in `debugging.md` doc?

**Review by deadwind4 — COMMENTED** [review]
Could you add a section in debugging.md doc?

**Review by deadwind4 — CHANGES_REQUESTED** [review]
Could you add a section in `debugging.md` doc?

**Comment by jiaoqingbo** [comment]
> Could you add a section in `debugging.md` doc?

If https://github.com/apache/incubator-kyuubi/pull/2418 works, Flink's implementation should be consistent with Hive Trino. I will implement this pr and update the documentation after 2418 is discussed if it is possible

**Comment by jiaoqingbo** [comment]
> Could you add a section in `debugging.md` doc?

If https://github.com/apache/incubator-kyuubi/pull/2418 works, Flink's implementation should be consistent with Hive and Trino as @yaooqinn  said. I will implement this pr and update the documentation after 2418 is discussed if it is possible。also cc @SteNicholas  @yaooqinn

**Pull request closed without merging**
