### PR TITLE
Use ServicesResourceTransformer to concatenating service entries

### PR DESCRIPTION
**Pull request by hddong**
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by hddong** [comment]
cc @pan3793 @wForget

**Comment by pan3793** [comment]
Would you please check the following items in the shaded jar?

- is every third-party class relocated properly？
- are the relocated classes listed in the final services manifest?

**Comment by hddong** [comment]
> * are the relocated classes listed in the final services manifest?

Yes, I have checked it, all relocated properly.

**Review by cxzl25 — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master/1.6

**Pull request closed without merging**
