### PR TITLE
[KYUUBI #2905][DOCS] Update the number of new committers in MATURITY.md

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

update new committers number: 2 -> 6

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @yaooqinn

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by yaooqinn** [comment]
maybe we shall update other places of MATURITY too

**Comment by ulysses-you** [comment]
thanks, merging to master

**Pull request closed without merging**
