### PR TITLE
[KYUUBI #2859][SUB-TASK][KPIP-4] Support `--conf` for kyuubi-ctl

### LINKED ISSUE #2859: [SUB-TASK][KPIP-4] Support to retry the delete batch request in kyuubi rest command line
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

sub task of #2240

### Motivation

_No response_

### Describe the solution

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

To close #2859 

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
cc @lightning-L  @ulysses-you

**Comment by ulysses-you** [comment]
test failed ..

**Comment by turboFei** [comment]
> test failed ..

thanks, fixedd

**Comment by turboFei** [comment]
I will split the pr and refine the batch command in another pr.

**Comment by turboFei** [comment]
Refine the batch commands in #2889

**Review by ulysses-you — APPROVED** [review]

**Pull request closed without merging**
