### PR TITLE
Bump delta from 2.1.1 to 2.2.0

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

https://github.com/delta-io/delta/releases/tag/v2.2.0

### _How was this patch tested?_

Pass CI.

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by Yikf** [comment]
It would be better if you filled out an issue for this

**Comment by pan3793** [comment]
> It would be better if you filled out an issue for this

It's fine to send PR directly, as long as providing clear description.

**Comment by Yikf** [comment]
Got it @pan3793

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
