### PR TITLE
Fix flaky test - AdminResourceSuite: delete engine - user share level 

### LINKED ISSUE #3751: [TEST] AdminResourceSuite: delete engine - user share level *** FAILED ***
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

https://github.com/apache/incubator-kyuubi/actions/runs/3382529618/jobs/5617547122

```
AdminResourceSuite:
- refresh Hadoop configuration of the kyuubi server
- delete engine - user share level *** FAILED ***
  List("serviceUri=localhost:35305;version=1.7.0-SNAPSHOT;refId=fde843a4-b580-423b-9705-cacb04e18070;sequence=0000000000") had size 1 instead of expected size 0 (AdminResourceSuite.scala:103)
```

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

close #3751

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
UT passed one time, try again

image

**Comment by turboFei** [comment]
retrying https://github.com/apache/incubator-kyuubi/actions/runs/3384044997

**Comment by turboFei** [comment]
Passed again

image

**Comment by turboFei** [comment]
try again

**Comment by wForget** [comment]
> cc @cfmcgrady @wForget
> 
> I do not know why indeed.

I'm also confused about this, but this fix looks good.

**Comment by wForget** [comment]
> cc @cfmcgrady @wForget
> 
> I do not know why indeed.

Is it possible that `serviceNode: PersistentNode` is automatically recreate after being deleted?

**Comment by turboFei** [comment]
> Is it possible that serviceNode: PersistentNode is automatically recreate after being deleted?

Not sure, but it did can be deleted finally.

**Comment by turboFei** [comment]
```
- JpsApplicationOperation with jstat *** FAILED ***
  null equaled null (JpsApplicationOperationSuite.scala:56)
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT    CGC    CGCT     GCT   
  0.00 100.00  92.04  78.54  96.79  87.17     45    0.786     0    0.000    22    0.470    1.255
  0.00 100.00  93.81  78.54  96.79  87.17     45    0.786     0    0.000    22    0.470    1.255
```

**Review by wForget — APPROVED** [review]
LGTM

**Comment by turboFei** [comment]
thanks, merging to master

**Pull request closed without merging**
