### PR TITLE
[KYUUBI #2253] [Improvement] Trino Engine - Events support

### PR DESCRIPTION
**Pull request by zhaomin1423**
### _Why are the changes needed?_

add event support for trino engine.

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by hddong** [comment]
@zhaomin1423 There are some conflicts.

**Comment by zhaomin1423** [comment]
> @zhaomin1423 There are some conflicts.

fixed

**Comment by hddong** [comment]
@zhaomin1423 Thanks, LGTM.

**Review by hddong — APPROVED** [review]

**Comment by hddong** [comment]
@zhaomin1423 : Thanks, merging to master.

**Pull request closed without merging**
