### PR TITLE
[DOCS] Fix Getting Started With Kyuubi on Kubernetes

### PR DESCRIPTION
**Pull request by HYBG-1126**
### _Why are the changes needed?_

helm安装kyuubi服务完成后会提示：
```script
NAME: kyuubi-helm
LAST DEPLOYED: Wed Mar 16 13:14:32 2022
NAMESPACE: kyuubi
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
#
# Licensed to the Apache Software Foundation (ASF) under one or more
......

Get kyuubi expose URL by running these commands:
  **export NODE_PORT=$(kubectl get --namespace kyuubi -o jsonpath="{.spec.ports[0].nodePort}" services kyuubi-helm-nodeport)**
  export NODE_IP=$(kubectl get nodes --namespace kyuubi -o jsonpath="{.items[0].status.addresses[0].address}")
  echo $NODE_IP:$NODE_PORT
```

使用命令
```
export NODE_PORT=$(kubectl get --namespace kyuubi -o jsonpath="{.spec.ports[0].nodePort}" services kyuubi-helm-nodeport)
```
会得到一个报错：
```
Error from server (NotFound): services "kyuubi-helm-nodeport" not found
```
使用`kubectl get svc -A`，查询到namespace：kyuubi下只有一个service："kyuubi-svc"，运行
```
export NODE_PORT=$(kubectl get --namespace kyuubi -o jsonpath="{.spec.ports[0].nodePort}" services kyuubi-svc)
```
成功。so这里给的serviceName是否是错的？

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
@HYBG-1126 Thanks for reporting issue and sending PR, could you please make your description format looks better, it's hard to read for reviewers now.

cc @hddong

**Comment by hddong** [comment]
@HYBG-1126 : You can get correct command after `helm install`. It is Related to the helm project's name.

**Comment by hddong** [comment]
In the given example, the project's name is `kyuubi-helm` and svc is 'node-port' . So we get command with `kyuubi-helm-nodeport`.

**Comment by hddong** [comment]
image

**Comment by hddong** [comment]
@HYBG-1126 : Sorry, my mistake, you are right, it need to change to `kyuubi-svc`. Thanks.

**Review by hddong — APPROVED** [review]

**Comment by HYBG-1126** [comment]
抱歉，之前没有提交过pr，所以没有注意到格式问题，后面我会注意一下。

**Comment by pan3793** [comment]
Thanks @HYBG-1126 for contribution and @hddong for verification, merging to master/1.5

**Comment by pan3793** [comment]
@HYBG-1126 Seems you do not set your email in your GitHub profile, thus your contribution could not be counted, would you please update your GitHub profile?

```
Authored-by: liuzy04 <liuzy04@mail.jj.com>
```

**Comment by HYBG-1126** [comment]
yesterday my email is private,now it is public

**Comment by HYBG-1126** [comment]
您好，您把我的内部邮箱暴露出来了，我们公司有相应的审计，麻烦您删除一下，感谢。

**Comment by pan3793** [comment]
The email address comes from your [git commit](https://github.com/apache/incubator-kyuubi/commit/ea152f33250939ed17e1af24bbb118dfaba9dc68.patch), I'm afraid we can not force push to overwrite the public branch, it will mess all developers local repo.

**Comment by pan3793** [comment]
I deleted my comment above, hope it impacts you less.

**Comment by HYBG-1126** [comment]
ok，问题解决就行，我还需要继续学习，给您添麻烦了。

**Pull request closed without merging**
