### PR TITLE
[KYUUBI #1241] Build Spark extension fat jar with common module

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

see https://github.com/apache/incubator-kyuubi/issues/1241

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @pan3793 @cfmcgrady @yaooqinn

**Comment by cfmcgrady** [comment]
It seems the GA hangs.

**Comment by ulysses-you** [comment]
thank you for review. GA passed, so I'm merging to master!

**Comment by yaooqinn** [comment]
> It seems the GA hangs.

is it related？

**Pull request closed without merging**
