### PR TITLE
[KYUUBI #3145] Bump log4j from 2.17.2 to 2.18.0

### PR DESCRIPTION
**Pull request by ParisaTork**
### _Why are the changes needed?_

Bumping log4j from 2.17.2 to 2.18.0 will reduce the risk of CVEs.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request (Ran ```./build/mvn clean test``` - see screenshots below for more info)

### CODE REVIEW

**Comment by ParisaTork** [comment]
Test Result Screenshots after ```./build/mvn clean test``` was run:
Screenshot 1
Screenshot 2

**Comment by pan3793** [comment]
Please run `build/mvn clean install -DskipTests && ./build/dependency.sh --replace` to update dependency list as well

**Comment by ParisaTork** [comment]
Thanks @pan3793 - the dependency list has been updated :)

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
