### PR TITLE
[KYUUBI #905] [MINOR] clear handleToTSessionHandle in KyuubiOperationManager

### PR DESCRIPTION
**Pull request by BoyangYue**
### _Why are the changes needed?_

To clear deprecated handleToTSessionHandle in KyuubiOperationManager.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by byyue** [comment]
@pan3793 Hi, another better version has been merged to master. See https://github.com/apache/incubator-kyuubi/pull/911.

**Comment by pan3793** [comment]
Yeah, I see. BTW, in some cases, I think that reuse the existing PR is a better choise instead of open a new one.

**Comment by byyue** [comment]
> Yeah, I see. BTW, in some cases, I think that reuse the existing PR is a better choise instead of open a new one.

Got it. By the way, since I'm still a beginner in Scala, feel free to assign me some more trivial tasks so that I can get familiar with this project and contribute gradually.

**Comment by pan3793** [comment]
Thank you for your enthusiasm for the Scala and Kyuubi community.

**Pull request closed without merging**
