### PR TITLE
Add `improvement` issue template

### PR DESCRIPTION
**Pull request by link3280**
### _Why are the changes needed?_

As disused in https://github.com/apache/incubator-kyuubi/discussions/1824.

Below is a preview of the new issue template.

截屏2022-01-28 23 06 12

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
shall we also add those checkboxes like bug an feature template？

**Comment by link3280** [comment]
> shall we also add those checkboxes like bug an feature template？

+1

**Comment by ulysses-you** [comment]
thank you @link3280 , please also update the snapshot in PR description

**Comment by link3280** [comment]
> thank you @link3280 , please also update the snapshot in PR description

@ulysses-you snapshot updated.

**Review by yaooqinn — APPROVED** [review]
lgtm

**Review by turboFei — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to master

**Pull request closed without merging**
