### PR TITLE
[KYUUBI #2012] rename EventLoggingService and creates an correct directory

### LINKED ISSUE #2012: [Bug] EventLoggingService creates an incorrect directory
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

In EventLoggingService.scala ，when EventLoggerType is set to Json
kyuubi created an error directory, it should not be the ENGINE_EVENT_JSON_LOG_PATH but the SERVER_EVENT_JSON_LOG_PATH

微信图片_20220304165614
微信图片_20220304165633

### Affects Version(s)

master

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jiaoqingbo**
### _Why are the changes needed?_

Fix #2012 #1180 

In `EventLoggingService`, when `EventLoggerType` is set to `JSON`
Kyuubi creates an error directory, it should not be the `ENGINE_EVENT_JSON_LOG_PATH` but the `SERVER_EVENT_JSON_LOG_PATH`.
微信图片_20220304165614
微信图片_20220304165633

rename `EventLoggingService` in `kyuubi-server` to `KyuubiEventLoggingService`
rename `EventLoggingService`  in `kyuubi-spark-sql-engine` to `SparkEventLoggingService`

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Check style failed, please run `dev/reformat` to fix it.

**Comment by jiaoqingbo** [comment]
can help me to review the code? @pan3793 @yaooqinn

**Review by pan3793 — APPROVED** [review]
LGTM

**Comment by yaooqinn** [comment]
thanks, merged to master

**Pull request closed without merging**
