### PR TITLE
[KYUUBI #3857] AlterViewAsCommand should skip checking query privileges

### LINKED ISSUE #3857: [Bug][Authz] AlterViewAsCommand should skip checking query privileges
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

only check the view privileges

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to fix.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by jiaoqingbo**
### _Why are the changes needed?_

fix #3857 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by jiaoqingbo** [comment]
PTAL @pan3793

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by yaooqinn** [comment]
on second thought, the original behavior is valid and safe..

**Review by yaooqinn — CHANGES_REQUESTED** [review]
sorry, my mistake

**Comment by jiaoqingbo** [comment]
> on second thought, the original behavior is valid and safe..

ok i will close this pr

**Pull request closed without merging**
