### PR TITLE
[WIP][KYUUBI #2370] Fix travis with missing JAVA_HOME

### PR DESCRIPTION
**Pull request by zwangsheng**
### _Why are the changes needed?_

According to #2370, seems JAVA_HOME does not work. Let's explicitly declare JAVA_HOME in .travis.yaml

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by zwangsheng** [comment]
Using Github to test PR, still in progress.

**Comment by zwangsheng** [comment]
This is a friendly ping @martin-g. 
Hello, may I ask if you have time to help check the problems of `Travis CI`? Thanks.

**Comment by martin-g** [comment]
I will take a look!

**Comment by martin-g** [comment]
It seems for some reason TravisCI stopped exporting JAVA_HOME ...
```
- hive process builder *** FAILED ***

  org.apache.kyuubi.KyuubiSQLException: JAVA_HOME is not set! For more information on installing and configuring JAVA_HOME, please visit https://kyuubi.apache.org/docs/latest/deployment
```

I will set it explicitly! PR is coming!

**Comment by martin-g** [comment]
https://github.com/apache/incubator-kyuubi/pull/2385

**Comment by martin-g** [comment]
Oh, I just realized the this PR is a fix for the same problem ...
I just checked the errors and went to conclusions...

Let me take a deeper look here!

**Comment by martin-g** [comment]
Your fix looks good to me!
But it seems TravisCI erases the env var at some point before executing the tests.
At https://github.com/apache/incubator-kyuubi/pull/2385 I try to export it in `before_script` step which is just before the `script` where we execute the tests. Hopefully this will solve it!

**Comment by martin-g** [comment]
This PR could be closed.

**Comment by turboFei** [comment]
thanks, JAVA_HOME issue fixed by #2385

**Comment by zwangsheng** [comment]
Thanks for your help! @martin-g

**Pull request closed without merging**
