### PR TITLE
Refine KyuubiStatementEvent

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

1. When a statement error happened, the event will be logged twice, in `setState` and `setException`, we fix it
2. We break down KyuubiStatementEvent into three parts - statement basis, status, and sessionId/user, see the improved comments
3. log the remote operation handle too

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by pan3793** [comment]
It seems a breaking change, will it affect users?

**Comment by yaooqinn** [comment]
> It seems a breaking change, will it affect users?
yes, but this feature is still experimental so far.

**Comment by pan3793** [comment]
Marked `release highlight`

**Pull request closed without merging**
