### PR TITLE
[KYUUBI #1769][FOLLOWUP] Exclude log4j 12 deps from spark-hive and fix detect deps change workflow

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

The previous PR did not handle log4j 1.2 deps of `spark-hive`, and the current detect deps change workflow has the dirty cache issue, this PR also fix it.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
```
Warning:  [Warn] /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-hive-beeline/src/main/java/org/apache/hive/beeline/KyuubiCommands.java:483: Character(char) in java.lang.Character has been deprecated
Warning:  Scalastyle:check is skipped as scalastyle.skip=true
Error: ] : Symbol 'type org.apache.log4j.AppenderSkeleton' is missing from the classpath.
```

**Comment by turboFei** [comment]
> ```
> Warning:  [Warn] /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-hive-beeline/src/main/java/org/apache/hive/beeline/KyuubiCommands.java:483: Character(char) in java.lang.Character has been deprecated
> Warning:  Scalastyle:check is skipped as scalastyle.skip=true
> Error: ] : Symbol 'type org.apache.log4j.AppenderSkeleton' is missing from the classpath.
> ```

let me try to revert the change for kyuubi-hive-beeline module

**Comment by turboFei** [comment]
you can rebase on #1854 if it is merged.

**Comment by turboFei** [comment]
```
Dependency List Changed Detected: 
78a79 > log4j/1.2.17//log4j-1.2.17.jar 96a98 > slf4j-log4j12/1.7.30//slf4j-log4j12-1.7.30.jar
> log4j/1.2.17//log4j-1.2.17.jar
96a98
> slf4j-log4j12/1.7.30//slf4j-log4j12-1.7.30.jar ]]
To update the dependency file, run './build/dependency.sh --replace'.
+ echo 'Dependency List Changed Detected: '
+ echo 78a79 '>' log4j/1.2.17//log4j-1.2.17.jar 96a98 '>' slf4j-log4j12/1.7.30//slf4j-log4j12-1.7.30.jar
+ echo 'To update the dependency file, run '\''./build/dependency.sh --replace'\''.'
+ exit 1
```

**Comment by pan3793** [comment]
@turboFei The detect dependencyList changes workflow failed because of cache issue, I updated and solved it, please take a look again.

**Review by turboFei — APPROVED** [review]
LGTM

**Comment by turboFei** [comment]
thanks, merged to master

**Pull request closed without merging**
