### PR TITLE
[WIP][KYUUBI #2499] Add Iceberg and minimal DSv2 commands to Authz plugin

### PR DESCRIPTION
**Pull request by minyk**
### _Why are the changes needed?_

Current Authz plugin cannot handle DSv2 and Iceberg related commands. Add them to the module.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by minyk** [comment]
I'm writing unit tests, but I'm stuck to add Iceberg extensions for testing. For testing Iceberg commands, I need to add `IcebergSparkSessionExtensions` when `SparkSession.builder()`

```scala
  protected val extension: SparkSessionExtensions => Unit = _ => Unit
  protected lazy val spark: SparkSession = {
  ...
    SparkSession.builder()
      .master("local")
      .config("spark.ui.enabled", "false")
      .config("javax.jdo.option.ConnectionURL", s"jdbc:derby:;databaseName=$metastore;create=true")
      .config("spark.sql.catalogImplementation", catalogImpl)
      .config(
        "spark.sql.warehouse.dir",
        Utils.createTempDir(namePrefix = "spark-warehouse").toString)
      .withExtensions(extension)
      .getOrCreate()
  }
```

My scala understanding is not good, so I'm lookging for help.

**Comment by ulysses-you** [comment]
hi @minyk  have you seen the test class `IcebergSuiteMixin` in kyuubi-common module ? it should help

**Comment by minyk** [comment]
> hi @minyk have you seen the test class `IcebergSuiteMixin` in kyuubi-common module ? it should help

@ulysses-you thank you, I missed that.

**Comment by minyk** [comment]
I'm still working on unit test.

**Comment by minyk** [comment]
PR #2675 contains some V2Commands, so I would like to drop V2 related code in this PR, then mainly focused on Iceberg commands.
How about this? @yaooqinn

**Comment by minyk** [comment]
that seems right. I will close this PR and make an issue for v2 commands first.

**Comment by yaooqinn** [comment]
yea, let's walk through builtin DSv2 statements first

**Pull request closed without merging**
