### PR TITLE
[KYUUBI #2032] Hive Backend Engine - new APIs with hive-service-rpc 3.1.2 - SetClientInfo

### PR DESCRIPTION
**Pull request by yangrong688**
### _Why are the changes needed?_

Hive Backend Engine - new APIs with hive-service-rpc 3.1.2 - SetClientInfo

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yangrong688** [comment]
cc @SteNicholas

**Comment by yaooqinn** [comment]
Hi @yangrong688 , thanks for the PR, but I took a rough look overall, but I can't understand what we are doing here

**Comment by yangrong688** [comment]
> Hi @yangrong688 , thanks for the PR, but I took a rough look overall, but I can't understand what we are doing here
@yaooqinn  I'm sorry to make you confused, I have implemented SetClientInfo based on HIVE-18240, could you please give me some guide to improve this pr.

ref:
https://issues.apache.org/jira/browse/HIVE-18240?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16959838#comment-16959838

**Comment by ulysses-you** [comment]
there are some conflicts

**Comment by yangrong688** [comment]
> there are some conflicts

I will resolve later.

**Pull request closed without merging**
