### PR TITLE
[KYUUBI #1449] Fix when KyuubiServer initialize fail but not exit

### PR DESCRIPTION
**Pull request by zhenjiaguo**
### _Why are the changes needed?_

Kyuubi server should exit when initialize fail.

Detail see #1449.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
can you check the jstack to see which non-daemon thread prevents termination when an exception occurs?

**Comment by zhenjiaguo** [comment]
> can you check the jstack to see which non-daemon thread prevents termination when an exception occurs?

I use Arthas to see still running thread: 
```shell
"NIOServerCxn.Factory:/192.168.72.190:2181" Id=21 RUNNABLE (in native)
    at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
    at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
    at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by yaooqinn** [comment]
> > can you check the jstack to see which non-daemon thread prevents termination when an exception occurs?
> 
> I use Arthas to see, Non-daemon thread is:
> 
> ```shell
> "SessionTracker" Id=22 TIMED_WAITING on org.apache.zookeeper.server.SessionTrackerImpl@5344d655
>     at java.lang.Object.wait(Native Method)
>     -  waiting on org.apache.zookeeper.server.SessionTrackerImpl@5344d655
>     at org.apache.zookeeper.server.SessionTrackerImpl.run(SessionTrackerImpl.java:147)
> ```
> 
> Thread states are `TIMED_WAIT`.

Does this issue only occur when using embedded Zookeeper？

**Comment by zhenjiaguo** [comment]
> > > can you check the jstack to see which non-daemon thread prevents termination when an exception occurs?
> > 
> > 
> > I use Arthas to see, Non-daemon thread is:
> > ```shell
> > "SessionTracker" Id=22 TIMED_WAITING on org.apache.zookeeper.server.SessionTrackerImpl@5344d655
> >     at java.lang.Object.wait(Native Method)
> >     -  waiting on org.apache.zookeeper.server.SessionTrackerImpl@5344d655
> >     at org.apache.zookeeper.server.SessionTrackerImpl.run(SessionTrackerImpl.java:147)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thread states are `TIMED_WAIT`.
> 
> Does this issue only occur when using embedded Zookeeper？

YES, It causes by `zkServer.start()`. It has a thread still running when `KyuubiServer` initialize fail. 
To make sure of this, I configure external zookeeper to confirm. It can exit when `KyuubiServer` initialize fail. 

What do you think set embedded Zookeeper run as daemon thread, or do you have a better way to resolve it?

**Comment by yaooqinn** [comment]
> > > > can you check the jstack to see which non-daemon thread prevents termination when an exception occurs?
> > > 
> > > 
> > > I use Arthas to see, Non-daemon thread is:
> > > ```shell
> > > "SessionTracker" Id=22 TIMED_WAITING on org.apache.zookeeper.server.SessionTrackerImpl@5344d655
> > >     at java.lang.Object.wait(Native Method)
> > >     -  waiting on org.apache.zookeeper.server.SessionTrackerImpl@5344d655
> > >     at org.apache.zookeeper.server.SessionTrackerImpl.run(SessionTrackerImpl.java:147)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Thread states are `TIMED_WAIT`.
> > 
> > 
> > Does this issue only occur when using embedded Zookeeper？
> 
> YES, It causes by `zkServer.start()`. It has a thread still running when `KyuubiServer` initialize fail. To make sure of this, I configure external zookeeper to confirm. It can exit when `KyuubiServer` initialize fail.
> 
> What do you think set embedded Zookeeper run as daemon thread, or do you have a better way to resolve it?

maybe we can stop the zkServer here, if ` zkServer.getServiceState == started`?

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master and v1.4.1

**Pull request closed without merging**
