### PR TITLE
[CI] Run install before checking style

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

To avoid unexpected errors on bumping version and adding new modules.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by cfmcgrady** [comment]
Do we have a lightweight approach to check if the snapshot is available instead install the project directly?

**Comment by pan3793** [comment]
I think no

**Comment by yaooqinn** [comment]
able to trigger via a new module?

**Comment by cfmcgrady** [comment]
how about

```
mvn dependency:resolve -DincludeGroupIds="org.apache.kyuubi" -DincludeScope="compile" -DexcludeTransitive=true
```

[1] https://maven.apache.org/plugins/maven-dependency-plugin/usage.html#dependency:resolve
[2] https://maven.apache.org/plugins/maven-dependency-plugin/resolve-mojo.html

**Comment by cfmcgrady** [comment]
> how about
> 
> ```
> mvn dependency:resolve -DincludeGroupIds="org.apache.kyuubi" -DincludeScope="compile" -DexcludeTransitive=true
> ```

raised a new PR based on this idea. #3422

**Comment by pan3793** [comment]
Close and in favor #3422

**Pull request closed without merging**
