### PR TITLE
[DOC] Update collaborators page and correct terminology KPIP usage

### LINKED ISSUE #876: [Typo] Change KPIP to KBIP in the official web site.
### 1. Describe the bug

https://kyuubi.apache.org/improvement-proposals.html

Search "KPIP"

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

Partly fix #876

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
please link  #876, cc @yanghua

**Review by yanghua — APPROVED** [review]
+1 LGTM

**Comment by pan3793** [comment]
Thanks for the review, merging to master.

**Comment by pan3793** [comment]
@yaooqinn The doc site seems out of date, would you please have a check?

**Pull request closed without merging**
