### PR TITLE
[KYUUBI #2084][FOLLOWUP] Support arbitrary parameters for KyuubiConf

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

In this PR, we narrow the scope of 8f15622d9beef8d3b15602f3180a21ec86c75623 to support arbitrary parameters which configured in kyuubi-defaults.conf only.

We shall avoid propagating all `sys.props` of Kyuubi server to engine side, which is a dangerous behavior

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @jiaoqingbo, I modify your original PR a bit to only support arbitrary configs in `kyuubi-defaults.conf`, then we don't need to handle hundreds of jvm defaults, WDYT?

also cc @SteNicholas @ulysses-you @pan3793 @turboFei

**Comment by ulysses-you** [comment]
the idea looks reasonable

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by jiaoqingbo** [comment]
> cc @jiaoqingbo, I modify your original PR a bit to only support arbitrary configs in `kyuubi-defaults.conf`, then we don't need to handle hundreds of jvm defaults, WDYT?
> 
> also cc @SteNicholas @ulysses-you @pan3793 @turboFei

Look good to me ，sorry for the late reply

**Pull request closed without merging**
