### PR TITLE
[KYUUBI #1903] Add GetTableTypes for trino engine

### PR DESCRIPTION
**Pull request by SteNicholas**
### _Why are the changes needed?_

Add GetTableTypes for trino engine.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by SteNicholas** [comment]
@hddong, could you please review this simple pull request?

**Review by hddong — APPROVED** [review]

**Comment by hddong** [comment]
@SteNicholas : Thanks, LGTM

**Comment by SteNicholas** [comment]
@hddong, the result of CI is passed. Please help to merge.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
