### PR TITLE
Make SESSION_ENGINE_LAUNCH_ASYNC true by default

### PR DESCRIPTION
**Pull request by turboFei**
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
this is a good choice after ASYNC is finally stable, maybe we shall do this in v1.5.0

**Comment by turboFei** [comment]
sure

**Review by yaooqinn — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merging to master

**Comment by zinking** [comment]
@turboFei  can you provide a little context on the significance of `launchAsync` here ?  is it just to unblock the initialization process of session creation? 

or in other way,  do we still need async = false ?  why

**Pull request closed without merging**
