### PR TITLE
[KYUUBI #3666][Subtask] Support {OWNER} variable for queries run on CatalogV2

### PR DESCRIPTION
**Pull request by zhouyifan279**
### _Why are the changes needed?_
Subtask of #3607 

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by zhouyifan279** [comment]
cc @bowenliang123 @yaooqinn

**Review by bowenliang123 — APPROVED** [review]

**Comment by bowenliang123** [comment]
LGTM.

**Comment by bowenliang123** [comment]
@zhouyifan279  it is possible to move ut from iceberg catalog to v2 jdbc catalog with in mem db for less file footprint for testing?

**Comment by zhouyifan279** [comment]
> @zhouyifan279 it is possible to move ut from iceberg catalog to v2 jdbc catalog with in mem db for less file footprint for testing?

v2 jdbc catalog table does not have a owner property.

**Comment by bowenliang123** [comment]
> v2 jdbc catalog table does not have a owner property.
OK, let's leave it there.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
