### PR TITLE
[KYUUBI #1005] ServiceDiscoverySuite fails if hostname contains uppercase letter

### PR DESCRIPTION
**Pull request by zhouyifan279**
### _Why are the changes needed?_

Executing test case "ServiceDiscoverySuite @set up zookeeper auth" on a Linux host named "KYUUBI" fails.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by zhouyifan279** [comment]
@ulysses-you @yaooqinn @pan3793, could you take a review, thanks.

**Comment by pan3793** [comment]
Thanks for the PR, this should also fix the failure on WSL2.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master/1.3

**Comment by ulysses-you** [comment]
late lgtm

**Pull request closed without merging**
