### PR TITLE
[KYUUBI #1209] kyuubi.engine.share.level.subdomain can be more tolerant

### PR DESCRIPTION
**Pull request by Eli-Young**
feature: kyuubi.engine.share.level.subdomain can be more tolerant
now end-user can configure kyuubi.engine.share.level.subdomain by zookeeper valid path
I refer to the zookeeper doc http://zookeeper.apache.org/doc/r3.7.0/zookeeperProgrammers.html#:~:text=ZooKeeper%20Basic%20Operations.-,The%20ZooKeeper%20Data%20Model,-ZooKeeper%20has%20a
and source code:
https://github.com/apache/zookeeper/blob/master/zookeeper-server/src/main/java/org/apache/zookeeper/common/PathUtils.java#:~:text=public%20static%20void-,validatePath,-(String%20path)%20throws

### CODE REVIEW

**Comment by TyrealBM** [comment]
@yaooqinn  Thank you for your review,  I listened to your opinion and i have fixed it

**Comment by yaooqinn** [comment]
Hi @TyrealBM you need export `KYUUBI_UPDATE=1` then run the whole test locally to auto-generate the doc change.

**Comment by yaooqinn** [comment]
thanks @TyrealBM for your first contribution, merged to master

**Comment by yaooqinn** [comment]
FYI, `guoqing.yang <guoqing.yang@advance.ai>` can not be recognized by Github, it's better to add the email to you Github account

**Comment by ulysses-you** [comment]
thank you @TyrealBM for the contribution. `Kyubbi` is wrong, it's `Kyuubi` : )

**Pull request closed without merging**
