### PR TITLE
[IT][CI] CI build kyuubi docker image should using mvn_args to speed up 

### PR DESCRIPTION
**Pull request by zwangsheng**
### _Why are the changes needed?_

CI using `build/dockerfile` to build kyuubi docker image, which will build distribution frist.

We should pass servals maven args to help build speed up.

We only test spark engine for kyuubi on kubernetes it test, so we use hive and flink provided.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

- [x] Wait CI

### CODE REVIEW

**Comment by zwangsheng** [comment]
Before:
WX20221206-111107
After:

**Comment by zwangsheng** [comment]
For IT CI `dockerfile` related, friendly ping @cfmcgrady @pan3793

**Comment by cfmcgrady** [comment]
#3854 introduced the `fast` profile, can we reuse it?

**Comment by zwangsheng** [comment]
> #3854 introduced the `fast` profile, can we reuse it?

Thanks for your info, but in this IT Test case, we need spark binary, should not skip spark download.

**Review by cfmcgrady — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
