### PR TITLE
Build and test all modules on Linux ARM64

### PR DESCRIPTION
**Pull request by martin-g**
### _Why are the changes needed?_

This is a follow-up of #1918
There were some problems with Zookeeper and because of that only the tests of `kyuubi-common` module were enabled.
I've just tested latest `master` on my Linux ARM64 machine and now the Zookeeper related tests pass! 

### _How was this patch tested?_

I've executed `mvn clean install` locally and many more Maven modules were successfully built and tested! 
There was a test failure in the Flink related tests. I want to see whether the same will fail at TravisCI too. If it does then I will disable the Flink module in .travisci.yaml until it is resolved too.

### CODE REVIEW

**Comment by martin-g** [comment]
`mvn clean install -Dmaven.javadoc.skip=true -V` fully passed on my Linux ARM64 machine!

```
[INFO] Reactor Summary for Kyuubi Project Parent 1.6.0-SNAPSHOT:
[INFO] 
[INFO] Kyuubi Project Parent .............................. SUCCESS [  5.352 s]
[INFO] Kyuubi Project Common .............................. SUCCESS [01:36 min]
[INFO] Kyuubi Project Embedded Zookeeper .................. SUCCESS [ 16.049 s]
[INFO] Kyuubi Project High Availability ................... SUCCESS [ 26.478 s]
[INFO] Kyuubi Project Control ............................. SUCCESS [ 24.506 s]
[INFO] Kyuubi Project Metrics ............................. SUCCESS [ 25.234 s]
[INFO] Kyuubi Project Server Plugin ....................... SUCCESS [  2.621 s]
[INFO] Kyuubi Project Download Externals .................. SUCCESS [  7.707 s]
[INFO] Kyuubi Project Hive JDBC Client .................... SUCCESS [ 10.318 s]
[INFO] Kyuubi Project Hive JDBC Shaded Client ............. SUCCESS [ 48.858 s]
[INFO] Kyuubi Project Engine Flink SQL .................... SUCCESS [02:19 min]
[INFO] Kyuubi Project Engine Spark SQL .................... SUCCESS [07:47 min]
[INFO] Kyuubi Project Server .............................. SUCCESS [13:31 min]
[INFO] Kyuubi Project Engine Trino ........................ SUCCESS [02:18 min]
[INFO] Kyuubi Test Integration Tests ...................... SUCCESS [  1.950 s]
[INFO] Kyuubi Test Flink SQL IT ........................... SUCCESS [ 29.615 s]
[INFO] Kyuubi Project Hive Beeline ........................ SUCCESS [  2.284 s]
[INFO] Kyuubi Dev Code Coverage ........................... SUCCESS [  7.946 s]
[INFO] Kyuubi Project Engine Hive SQL ..................... SUCCESS [ 41.615 s]
[INFO] Kyuubi Project Assembly ............................ SUCCESS [  3.727 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31:47 min
[INFO] Finished at: 2022-03-14T10:37:53Z
[INFO] ------------------------------------------------------------------------
```

**Comment by yaooqinn** [comment]
thanks @martin-g for the help!

**Comment by martin-g** [comment]
I was not able to enable all modules.
The Flink related ones always fail with `exit code 137` - according to TravisCI support this means that there are not enough resources (memory ?!) on the VM.
At the end this PR just enables more Maven modules to be tested on ARM64.
Locally the full build passes on openEulerOS ARM64!

**Comment by martin-g** [comment]
@yaooqinn The build at TravisCI is green for all modules/jobs !

**Comment by yaooqinn** [comment]
+1, LGTM.

@martin-g thanks a lot for making this happen.

**Comment by yaooqinn** [comment]
thanks, merged to master!

**Pull request closed without merging**
