### PR TITLE
Global temp view should only exist in session catalog

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

DS v2 does not support view yet.
image

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
It's a long term bug, I mark it as a blocker for the ongoing release v1.5.2

**Comment by pan3793** [comment]
cc @ulysses-you

**Comment by ulysses-you** [comment]
Accroiding to the comments of how to resolve global_temp, we should mark global_temp as a special catalog. But given Spark has not supported v2 catalog for view, we can mark global_temp as a special table in spark built-in catalog spark_catalog.

https://github.com/apache/spark/blob/b5c7f34b576d25aec292c65e7565360d67142227/sql/catalyst/src/main/scala/org/apache/spark/sql/connector/catalog/LookupCatalog.scala#L113-L119

So the snapshot after correct the issue will be:
```
tpcd
  - sf0
  - tiny
  - sf1
  - sf10
  - sf30

spark_catalog
  - default
  - global_temp

......
```

If Spark supports v2 catalog for view in future, we can change it to:
```
tpcd
  - sf0
  - tiny
  - sf1
  - sf10
  - sf30

spark_catalog
  - default

global_temp

......
```

**Comment by ulysses-you** [comment]
cc @yaooqinn

**Comment by yaooqinn** [comment]
oh, I made this minor bug with the purpose to see if anyone use multi-cat feature

**Comment by yaooqinn** [comment]
An issue is better not to be a blocker when it is trivial or long-standing

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master/1.5

**Pull request closed without merging**
