### PR TITLE
[KYUUBI #3930] [Fix] Add synchronized for session signing 

### LINKED ISSUE #3930: [TEST] KYUUBI #3839 session user sign - check session user sign *** FAILED ***
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

https://github.com/apache/incubator-kyuubi/actions/runs/3637051754/jobs/6137647175
```
- KYUUBI #3839 session user sign - check session user sign *** FAILED ***
  java.lang.IllegalArgumentException: Illegal base64 character 2a
  at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
  at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
  at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
  at org.apache.kyuubi.util.SignUtils$.verifySignWithECDSA(SignUtils.scala:64)
  at org.apache.kyuubi.session.SessionSigningSuite.$anonfun$new$10(SessionSigningSuite.scala:81)
  at org.apache.kyuubi.session.SessionSigningSuite.$anonfun$new$10$adapted(SessionSigningSuite.scala:70)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3(JDBCTestHelper.scala:60)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3$adapted(JDBCTestHelper.scala:60)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
```

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

to close #3930 .

1.make SignUtils.signWithPrivateKey and synchronized
2.show exception with input string when base64 decoding failed

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @cfmcgrady @turboFei 
I'm not sure whether it fixes the problem, as no shared objects cross threads.
But making it synchronized might help.

**Comment by ulysses-you** [comment]
I faced this issue, let's get this in frist and see what happens

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by bowenliang123** [comment]
OK, thx. Let's keep eyes on it.

**Comment by bowenliang123** [comment]
OK, thx. Let's keep eyes on it. 

`synchronized` might not solved this problem, but should be ok for workaround.
No further suggestion to solve this for now.

My supplementary investigation covers,
- making sure of  key pair in singleton
- no shared object/ no mutable object across threads
- always new instance created during key pair generation, singing , encoder/decoder, including `Base.getDecoder`, `KeyFactory.getInstance`, `Signature. getInstance/update/verify`

**Comment by cfmcgrady** [comment]
It's not an issue about thread-safe.

The root cause is that spark will return a dummy text if the generated sign contains keywords in the `spark.redaction.regex` list

```
scala> spark.sql("set yy=yyyyytoken").show
+---+----------+
|key|     value|
+---+----------+
| yy|yyyyytoken|
+---+----------+


scala> spark.sql("set yy").show
+---+-------------------+
|key|              value|
+---+-------------------+
| yy|*********(redacted)|
+---+-------------------+
```

```
  java.lang.IllegalArgumentException: signature verification failed: publicKeyBase64:MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEGu++DbrARESJ10HKFAgiD6V7Ya5hDKiV9k78C5O4pAlIZgl1nDiQPn+Fj/9CgW+hZRrngYzC+6qe9Ov3uIsEHg==, signatureBase64:*********(redacted), plainText:user
```

cc @bowenliang123 @ulysses-you @turboFei

**Comment by ulysses-you** [comment]
thank you @cfmcgrady good finding ! The new error message in this pr seems work nice to help find the root cause. @bowenliang123 do you have time to fix it ?

**Comment by bowenliang123** [comment]
Sure, let me check again and try to fix it.
Although This PR would fix the problem and the added `synchronized` will be reverted,  it did help to see the error messages.
Thx to @cfmcgrady

**Comment by bowenliang123** [comment]
@cfmcgrady 's finding suggested we get getting the value in wrong way in UT, via "SET" in SQL with possibly redacted value. 
So we shall fix the ut to fetch the value in exact way in Authz , by getting the value via `spark.sparkContext.getLocalProperty`.

**Pull request closed without merging**
