### PR TITLE
Remove thrift request timeout for KyuubiSyncThriftClient

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

Remove thrift request timeout for KyuubiSyncThriftClient

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to master

**Comment by risyomei** [comment]
@yaooqinn @turboFei 
Hello, Sorry to disturb you while you are busy.

May I know the motivation for deleting the timeout?

**Comment by turboFei** [comment]
> @yaooqinn @turboFei 
> 
> Hello, Sorry to disturb you while you are busy.
> 
> 
> 
> May I know the motivation for deleting the timeout?

Remove it to prevent out of sequence issue.

**Comment by turboFei** [comment]
The thrift protocol does not support retry.

**Comment by risyomei** [comment]
@turboFei 
Thank you very much for your response.
Do you have a ticket to describe the "out of sequence issue"?

**Comment by turboFei** [comment]
> Do you have a ticket to describe the "out of sequence issue"?

about `out of sequence issue`.
```
In the context of Apache Thrift, "out of sequence issue" can refer to a situation where a Thrift server receives a message from a client that is out of order, meaning the server receives a message with a sequence number that is lower than expected.

This can happen if there is a delay or a disruption in the network communication between the client and the server, causing messages to be delivered out of order. If the server is not able to handle such out of sequence messages properly, it can result in incorrect behavior or even crashes.

To address this issue, Thrift includes a sequence number in each message to help the server determine if a message is out of order. If a server receives an out of sequence message, it can respond with an error message indicating the issue, or it can buffer the message until the expected sequence number is received.

Thrift also provides an option for clients to request ordered delivery of messages, which instructs the server to buffer and deliver messages in the correct order, even if they arrive out of sequence. This option can be useful in situations where network disruptions are common, but it can also impact performance, as buffering and reordering messages can introduce additional latency.
```

For example: 

1. client send fetchResult request  -> timeout , then client does not receive the fetchResult response.
2. client send getOpStatus request -> then receive the last `fetchResult response`(out of sequence because expected result is getOpStatus response`

**Comment by risyomei** [comment]
@turboFei 
Thank you very much for your explanation.
It's very easy to follow!

> client send fetchResult request -> timeout , then client does not receive the fetchResult response.
client send getOpStatus request -> then receive the last fetchResult response(out of sequence because expected result is getOpStatus response`

By the way, I have found a possible issue (https://github.com/apache/kyuubi/issues/4457) that are kind of related to this issue.
It will be very helpful if you can take a look at that as well 🙇‍♂️

**Pull request closed without merging**
