### PR TITLE
Fix minikube test

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

change the k8s-it serviceaccount to kyuubi instead of default

### _How was this patch tested?_
Pass CI

### CODE REVIEW

**Comment by ulysses-you** [comment]
I tune the  k8s-it serviceaccount to **kyuubi** instead of **default**, FYI @pan3793 @yaooqinn

**Review by pan3793 — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by bydeath** [comment]
I am using master-snapshot image of November 2, 2022, why it still use default serviceaccount?

**Comment by ulysses-you** [comment]
@bydeath this pr only changes the CI serviceaccount , not about master-snapshot

**Pull request closed without merging**
