### PR TITLE
Add umbrella type issus template

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

Make issue easy to manage.

### _How was this patch tested?_
 https://github.com/ulysses-you/incubator-kyuubi/issues/1

image

image

### CODE REVIEW

**Comment by yaooqinn** [comment]
add `https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists` to instuctions?

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by timothy65535** [comment]
👍

**Comment by ulysses-you** [comment]
thanks for review, merging to master

**Pull request closed without merging**
