### PR TITLE
[KYUUBI #1784] Fix float types lose precision

### LINKED ISSUE #1784: [Bug] Spark engine float type lost  precision
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Query result of spark engine will lost precision when using float type，e.g. sql：
```sql
CREATE TABLE spark_catalog.`default`.src(KEY FLOAT, VALUE STRING) USING PARQUET;
INSERT INTO TABLE spark_catalog.`default`.src VALUES (0.1, "Xiao");
SELECT * FROM spark_catalog.`default`.src;
```

query result:
```
+----------------------+--------+
|         KEY          | VALUE  |
+----------------------+--------+
| 0.10000000149011612  | Xiao   |
+----------------------+--------+
1 row selected 
```

### Affects Version(s)

master

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

close #1784 

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
thanks for the quick fix！

**Comment by pan3793** [comment]
Does it also affect other engines?

**Comment by cfmcgrady** [comment]
> Does it also affect other engines?

Not clear, as I only have Spark runtime, I don't know the behavior of other engines.

I can help do some checks when I am free.

**Comment by ulysses-you** [comment]
shall we also fix it in row-based row set ?
https://github.com/apache/incubator-kyuubi/blob/916f81abaf46f1f28386aa57739cd84059b93dcd/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/schema/RowSet.scala#L177-L180

a simple test:
image

**Comment by cfmcgrady** [comment]
> Does it also affect other engines?

@pan3793 Flink/Trino also has the same issue and will file a separate PR to fix it.

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master/branch-1.4/branch-1.3

**Pull request closed without merging**
