### PR TITLE
[KYUUBI #1131][TEST] Move KyuubiHiveDriverSuite to kyuubi-spark-sql-engine module

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

It's pre-step of #1152, otherwise will cause circular dependence. 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
we'd better update https://github.com/apache/incubator-kyuubi/tree/master/kyuubi-hive-jdbc#readme

**Comment by pan3793** [comment]
> we'd better update https://github.com/apache/incubator-kyuubi/tree/master/kyuubi-hive-jdbc#readme

Yea, I see, will update it soon.

**Comment by pan3793** [comment]
Will update https://github.com/apache/incubator-kyuubi/tree/master/kyuubi-hive-jdbc#readme in #1149

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
