### PR TITLE
Make secret id static and remove thrift protocol from RPC handles

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

1. remove `thrift protocol version` from REST req and resp.
   - it's useless for this REST. It's not used for version check and not for result set determination.
   - it's not a part of TSessionHandle/TOperationHandle either. The protocol version is determined in open session phase and used both by the session and the within operations. It should not be set per request. 
2. Make secret-id static across rest/batch/jdbc APIs

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
```
Error:  /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-server/src/test/scala/org/apache/kyuubi/server/api/v1/BatchesResourceSuite.scala:438: value getBatchSessionHandle is not a member of org.apache.kyuubi.session.KyuubiSessionManager

```

**Comment by ulysses-you** [comment]
Seems clear to remove thrift protocol from RPC handles

**Review by turboFei — APPROVED** [review]
LGTM, thanks

**Comment by yaooqinn** [comment]
thanks, merged to master

**Pull request closed without merging**
