### PR TITLE
[DOC] Update kyuubi_layers.drawio to add driver layer

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

image

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
The S3 logo is not correct

**Comment by pan3793** [comment]
The Pandas logo is distorted

**Comment by pan3793** [comment]
YARN logo is small than others

**Comment by yaooqinn** [comment]
> The S3 logo is not correct

which part?

**Comment by yaooqinn** [comment]
image

**Review by pan3793 — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master

**Pull request closed without merging**
