### PR TITLE
[KYUUBI #1472] allow the engine not to self-terminate.

### PR DESCRIPTION
**Pull request by wForget**
### _Why are the changes needed?_

Allow the engine not to self-terminate.  For details: #1472.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by ulysses-you — APPROVED** [review]

**Review by pan3793 — CHANGES_REQUESTED** [review]
Use zero or negative to represent no limit.

**Review by pan3793 — APPROVED** [review]

**Comment by ulysses-you** [comment]
@wForget can you resolve the conflicts ? thank you !

**Review by yaooqinn — APPROVED** [review]

**Comment by wForget** [comment]
> @wForget can you resolve the conflicts ? thank you !

I have resolved it.

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
