### PR TITLE
Delete the swagger UI related resource files from the source folder

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

This pr aims to reduce the source file size.

This PR removes the swagger UI resource file in the folder `kyuubi-server/src/main/resources/org/apache/kyuubi/ui/swagger` which was introduced by [PR-2061](https://github.com/apache/incubator-kyuubi/pull/2061) , and now we rely on Maven dependency `org.webjars::swagger-ui::4.9.1` to package these resource files, we also add a new REST endpoint `/swagger-static/` for downloading these resource files

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
The alternative is to delete the `*.map` and `*es-bundle*` files.

```
(kyuubi) ➜  swagger git:(master) ✗ ll    
total 4096
-rw-r--r--  1 chengpan  staff   665B Jul 14 17:31 favicon-16x16.png
-rw-r--r--  1 chengpan  staff   628B Jul 14 17:31 favicon-32x32.png
-rw-r--r--  1 chengpan  staff   3.3K Jul 14 17:31 index.html
-rw-r--r--  1 chengpan  staff   3.3K Sep  7 20:14 oauth2-redirect.html
-rw-r--r--  1 chengpan  staff   1.0M Jul 14 17:31 swagger-ui-bundle.js
-rw-r--r--  1 chengpan  staff   317K Jul 14 17:31 swagger-ui-standalone-preset.js
-rw-r--r--  1 chengpan  staff   140K Jul 14 17:31 swagger-ui.css
-rw-r--r--  1 chengpan  staff   502K Jul 14 17:31 swagger-ui.js
(kyuubi) ➜  swagger git:(master) ✗ du -hd1
2.0M    .
```

**Comment by pan3793** [comment]
cc @yaooqinn, which way are you preferred?

**Review by cxzl25 — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
LGTM

**Comment by pan3793** [comment]
Thanks, merging to master/1.6

**Pull request closed without merging**
