### PR TITLE
[KYUUBI #2079] Update kyuubi layer source file to add flink and trino…

### PR DESCRIPTION
**Pull request by yanghua**
… engine

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yanghua** [comment]
The new image looks like this:

kyuubi_layers drawio

**Comment by yanghua** [comment]
New image:

kyuubi_layers drawio (1)

**Comment by yaooqinn** [comment]
lgtm，thanks

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master/branch-1.5

**Pull request closed without merging**
