### PR TITLE
[KYUUBI #3101] [Subtask][#3100] Build the content for extension points documentation

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

Build the content for extension points documentation, pre-work for #3100 

image

1. the extensions are divided into 2: server side and engine side extensions. (Do we have client side extension support?)
2. the server side authentication page is cross-referenced by the security section, see 1 in the picture.
3. the engine side ones are grouped by different compute frameworks.
4. connector is one type of extension, so we cross-reference the connector pages directly, see 2 & 3 in the picture.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @ulysses-you @turboFei @deadwind4, can you help review this?

**Comment by ulysses-you** [comment]
I see `connectors` is a part of extension, is it better to mark `connectors` as top level since it's quite important for lake house user

**Comment by yaooqinn** [comment]
hi @ulysses-you both connectors and security are top-level ones currently.

**Review by ulysses-you — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks @ulysses-you, merged to master

**Pull request closed without merging**
