### PR TITLE
Fix the kyuubi restful href link format issue

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

Now the href link format is not correct, we should add `/` at the tail for `/static` and `/swagger`.
FYI:
image

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by cfmcgrady** [comment]
It seems still does not work?

```
> curl http://${local-ip}:10099/swagger                                              
> curl http://${local-ip}:10099/swagger/ | head -n 3                                 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3381  100  3381    0     0   173k      0 --:--:-- --:--:-- --:--:--  173k
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with

```

**Comment by turboFei** [comment]
> It seems still does not work?
> 
> ```
> > curl http://${local-ip}:10099/swagger                                              
> > curl http://${local-ip}:10099/swagger/ | head -n 3                                 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  3381  100  3381    0     0   173k      0 --:--:-- --:--:-- --:--:--  173k
> <!--
>   ~ Licensed to the Apache Software Foundation (ASF) under one or more
>   ~ contributor license agreements.  See the NOTICE file distributed with
> ```

how about?

```
curl -L http://${local-ip}:10099/swagger              
```

For me, it works well with http, but fail on https.

**Comment by turboFei** [comment]
```
 ⚙ fwang12@KKXJXWYGVX  ~  curl -L http://hadoopkyuubi-0.hadoopkyuubihl.hadoopmaster-dev.svc.130.tess.io:10011 |head -10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2331  100  2331    0     0   2884      0 --:--:-- --:--:-- --:--:--  2884
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
 ⚙ fwang12@KKXJXWYGVX  ~  curl -L https://kyuubi.hadoop.qa.ebay.com |head -10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (7) Failed to connect to kyuubi.hadoop.qa.ebay.com port 80 after 213 ms: Connection refused
 ⚙ fwang12@KKXJXWYGVX  ~  curl -L https://kyuubi.hadoop.qa.ebay.com/static/ |head -10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2331  100  2331    0     0   2683      0 --:--:-- --:--:-- --:--:--  2729
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
 ⚙ fwang12@KKXJXWYGVX  ~ 
```

**Comment by cfmcgrady** [comment]
```console
 > curl -L http://${local-ip}:10099/swagger | head -n 3                                
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3381  100  3381    0     0   117k      0 --:--:-- --:--:-- --:--:--  117k
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
```

`curl` with `-L` works for me :)

**Review by cfmcgrady — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to master

**Pull request closed without merging**
