### PR TITLE
Refer the YarnApplicationState and FinalApplicationStatus to map application state

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

We shall respect the final application status first.

Otherwise, the batch state is not consisted with the app state.

FYI:
image
image

This pr refer the livy implementation: 

https://github.com/apache/incubator-livy/blob/50faa9f68a6f1c79f605a4cb70e452f9c7f21528/server/src/main/scala/org/apache/livy/utils/SparkYarnApp.scala#L236-L259

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
cc @ulysses-you @yaooqinn @pan3793

**Comment by pan3793** [comment]
I think it's good for Yarn Cluster mode, but there may some issues on Yarn client mode, see SPARK-36540.

**Comment by turboFei** [comment]
https://github.com/apache/incubator-livy/blob/50faa9f68a6f1c79f605a4cb70e452f9c7f21528/server/src/main/scala/org/apache/livy/utils/SparkYarnApp.scala#L236-L259

**Review by pan3793 — APPROVED** [review]

**Comment by turboFei** [comment]
> 
I think it's good for Yarn Cluster mode, but there may some issues on Yarn client mode, see SPARK-36540.


It should be fine, we also refer the process.exitValue.

**Review by ulysses-you — APPROVED** [review]

**Pull request closed without merging**
