### PR TITLE
Bump Zookeeper from 3.4.14 to 3.6.3

### LINKED ISSUE #1941: [Bug] Zookeeper 3.4 does not support JDK 17
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Env: AArach64 JDK-17 

`EmbeddedZookeeperSuite` failed because of [ZOOKEEPER-3779](https://issues.apache.org/jira/browse/ZOOKEEPER-3779)
```
10:37:41.862 ScalaTest-main-running-EmbeddedZookeeperSuite-SendThread(10.242.138.159:38827) WARN ClientCnxn: Session 0x0 for server 10.242.138.159/<unresolved>:38827, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address 10.242.138.159/<unresolved>:38827 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) [zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
```

### Affects Version(s)

master

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

#2040 adds the test to verify the compatibility for Zookeeper Server 3.4, I will rebase this PR after #2040 get merged.

Close #1941

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by SteNicholas — APPROVED** [review]
LGTM. cc @yaooqinn

**Comment by yaooqinn** [comment]
thanks @SteNicholas, this pr seems not ready for review it's blocked by https://github.com/apache/incubator-kyuubi/pull/2040

**Comment by pan3793** [comment]
> thanks @SteNicholas, this pr seems not ready for review it's blocked by #2040

Yea, marked this one as draft for now, I will address #2040 ASAP.

**Review by SteNicholas — APPROVED** [review]

**Comment by wForget** [comment]
I verified this patch is ok in our environment.

Environment:
+ Kyuubi zookeeper client version: 3.6.3
+ Zookeeper server version: 3.4.13

Check items:
+ Connect normally using Zookeeper Service Discovery mode.
+ Kyuubi server and Spark engine start normally without any error log.
+ `show databases` is OK.
+ `select statement` is OK.

**Comment by wForget** [comment]
run `bin/kyuubi-zk-cli` error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at org.apache.zookeeper.ZooKeeperMain.<clinit>(ZooKeeperMain.java:108)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

**Comment by pan3793** [comment]
`ClassNotFoundException: org.apache.commons.cli.ParseException` has been fixed by adding `common-cli` deps.

**Comment by pan3793** [comment]
Thanks, merging to master

**Comment by pan3793** [comment]
Reverted because breaks compatible of Zookeeper 3.4

```
Exception in thread "Thread-6" org.apache.kyuubi.KyuubiSQLException: Lock failed on path [/lock-test]
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient.tryWithLock(ZookeeperDiscoveryClient.scala:171)
	at org.apache.kyuubi.ha.client.DiscoveryClientTests.$anonfun$$init$$13(DiscoveryClientTests.scala:139)
	at org.apache.kyuubi.ha.client.DiscoveryClientTests.$anonfun$$init$$13$adapted(DiscoveryClientTests.scala:137)
	at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:36)
	at org.apache.kyuubi.ha.client.DiscoveryClientTests.$anonfun$$init$$12(DiscoveryClientTests.scala:137)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /lock-test/locks
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1734)
	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:454)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
	at org.apache.curator.framework.recipes.locks.StandardLockInternalsDriver.createsTheLock(StandardLockInternalsDriver.java:54)
	at org.apache.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:217)
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.internalLock(InterProcessMutex.java:232)
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:108)
	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.internalAcquire1Lease(InterProcessSemaphoreV2.java:344)
	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.acquire(InterProcessSemaphoreV2.java:284)
	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.acquire(InterProcessSemaphoreV2.java:246)
	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreMutex.acquire(InterProcessSemaphoreMutex.java:52)
	at org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient.tryWithLock(ZookeeperDiscoveryClient.scala:163)
	... 5 more
```

**Pull request closed without merging**
