### PR TITLE
[KYUUBI #1668] Implement ElasticSearchEventLogger to store KyuubiEvent to ElasticSearch.

### PR DESCRIPTION
**Pull request by wForget**
### _Why are the changes needed?_

Implement ElasticSearchEventLogger to store KyuubiEvent to ElasticSearch. #1668

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [X] Add screenshots for manual tests if appropriate
image

- [X] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Some questions:
1. Elasticsearch has potential license issue in recent versions, v7.10.2 is the latest version released in Apache License v2.
2. Have searched on maven central, the low level rest client `elasticsearch-rest-client` released in Apache License v2, seems OK to use, but some guy points that we need verify there is no files under other incompatible license included in jar before bundling the jar in our binary release tarball.
3. Elasticsearch seems has different API across there major releases, e.g. 6.x, 7.x and on going 8.x, some project like Apache Flink has specific module for specific major versions, how can Kyuubi achieve that?
4. I'm not sure if it's valued to add the integration test for this feature, if yes, maybe we can leverage Testcontainers to build such IT.

**Comment by wForget** [comment]
> 1. Elasticsearch has potential license issue in recent versions, v7.10.2 is the latest version released in Apache License v2.
> 2. Have searched on maven central, the low level rest client `elasticsearch-rest-client` released in Apache License v2, seems OK to use, but some guy points that we need verify there is no files under other incompatible license included in jar before bundling the jar in our binary release tarball.

Sorry, I am not familiar with these. Does it mean that I cannot use the 7.16.2 version of the `elasticsearch-rest-client`? If so, can you give me a recommended version?

> 3. Elasticsearch seems has different API across there major releases, e.g. 6.x, 7.x and on going 8.x, some project like Apache Flink has specific module for specific major versions, how can Kyuubi achieve that?

How about changing the module name to `kyuubi-event-logger-elasticsearch7`?

> 4. I'm not sure if it's valued to add the integration test for this feature, if yes, maybe we can leverage Testcontainers to build such IT.

I tried to use Testcontainers, but because of the windows development environment I used, it didn't run successfully. I will continue to try it if necessary.

**Comment by cody1993** [comment]
More logger will affect the sql performance, `ElasticSearchEventLogger` is not a good practice.

**Comment by wForget** [comment]
> More logger will affect the sql performance, `ElasticSearchEventLogger` is not a good practice.

The `ElasticSearchEventLogger` is optional, meanwhile I noticed #1798 that will make it async.

**Comment by wForget** [comment]
Close obsolete implementation. I can reopen it if needed.

**Pull request closed without merging**
