### PR TITLE
[TEST] Using  more light-weight SparkPi for batch related tests

### LINKED ISSUE #3114: Flaky Test: BatchesResourceSuite - expose the metrics with operation type and current state *** FAILED ***
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
BatchesResourceSuite:
- open batch session
kill: (27749): No such process
- get batch session list
- negative request
- batch sessions recovery
- get local log internal redirection
- delete batch internal redirection
- support to get the real client ip for http proxy use case
- expose the metrics with operation type and current state *** FAILED ***
  1 did not equal 0 (BatchesResourceSuite.scala:601)
```

### Actions URL

https://github.com/apache/incubator-kyuubi/runs/7442983919?check_suite_focus=true

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

Using more light-weight SparkPi example to prevent the GA OOM issue.

BTW, it should resolve #3114

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
```
 03:22:27.310 INFO org.apache.kyuubi.operation.BatchJobSubmission: Processing anonymous's query[29605780-1958-4cc9-a6ca-7a9b0eacbac5]: INITIALIZED_STATE -> PENDING_STATE, statement: BatchJobSubmission
  03:22:27.312 INFO org.apache.kyuubi.operation.BatchJobSubmission: Submitting SPARK batch[ad394003-6fbb-4df1-94a4-9f96d6641f20] job: /home/runner/work/incubator-kyuubi/incubator-kyuubi/externals/kyuubi-download/target/spark-3.1.3-bin-hadoop3.2/bin/spark-submit \
  	--class org.apache.spark.examples.SparkPi \
  	--conf spark.kubernetes.driver.label.kyuubi-unique-tag=ad394003-6fbb-4df1-94a4-9f96d6641f20 \
  	--conf spark.app.name=Spark Pi \
  	--conf spark.driver.memory=16m \
  	--conf spark.master=local \
  	--conf spark.yarn.tags=KYUUBI,ad394003-6fbb-4df1-94a4-9f96d6641f20 \
  	--conf kyuubi.client.ipAddress=127.0.0.1 \
  	--proxy-user anonymous /home/runner/work/incubator-kyuubi/incubator-kyuubi/externals/kyuubi-download/target/spark-3.1.3-bin-hadoop3.2/examples/jars/spark-examples_2.12-3.1.3.jar
  03:22:27.312 INFO org.apache.kyuubi.engine.ProcBuilder: Logging to /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-server/target/work/anonymous/kyuubi-spark-batch-submit.log.0
  03:22:28.470 INFO org.apache.kyuubi.operation.BatchJobSubmission: Processing anonymous's query[29605780-1958-4cc9-a6ca-7a9b0eacbac5]: PENDING_STATE -> RUNNING_STATE, statement: BatchJobSubmission
  03:22:29.514 INFO org.apache.kyuubi.operation.BatchJobSubmission: Processing anonymous's query[29605780-1958-4cc9-a6ca-7a9b0eacbac5]: RUNNING_STATE -> ERROR_STATE, statement: BatchJobSubmission, time taken: 1.044 seconds
  Error: A JNI error has occurred, please check your installation and try again
  Exception in thread "main" 
```

**Comment by turboFei** [comment]
Seems there is some issue SparkPi + JDK11.

**Review by cfmcgrady — APPROVED** [review]
LGTM

**Comment by turboFei** [comment]
thanks @cfmcgrady , merging to master

**Pull request closed without merging**
