### PR TITLE
[KYUUBI #1229] Fix met error when debug KyuubiServer in local IDE

### PR DESCRIPTION
**Pull request by charlesy6**
### _Why are the changes needed?_

When debug KyuubiServer in IDEA, IDEA: Intellij IDEA 2021.2(Ultimate Edition)

throw exception
```
/KyuubiHiveDriverSuite.scala:45:36
Class org.apache.hive.jdbc.HiveConnection not found - continuing with a stub.
    assert(connection.isInstanceOf[KyuubiConnection])
```

```
/KyuubiHiveDriverSuite.scala:47:34
Class org.apache.hive.jdbc.HiveDatabaseMetaData not found - continuing with a stub.
    assert(metaData.isInstanceOf[KyuubiDatabaseMetaData])
```

For more detail, please go to https://github.com/apache/incubator-kyuubi/issues/1229

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by timothy65535** [comment]
cc @pan3793, had tried run `KyuubiServer` after build kyuubi project.

**Comment by yaooqinn** [comment]
please add this to the umbrella @pan3793

**Comment by pan3793** [comment]
> Execute Build => Build Project(⌘+F9) or Rebuild Project before running the test.

@cfmcgrady Does this work for you?

**Comment by pan3793** [comment]
Thanks, merging to master.

**Pull request closed without merging**
