### PR TITLE
[DEPS] Bump jersey 2.30

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

Align with `spark-core`

https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.12/3.1.2
https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.12/3.0.3

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
@yanghua

**Comment by pan3793** [comment]
I'm a little surprised that Jetty pulls such a number of dependencies.

**Comment by yanghua** [comment]
+1, IMO, it does not affect the rest frontend service. Will verify later.

**Comment by ulysses-you** [comment]
thanks, merging to master

**Pull request closed without merging**
