### PR TITLE
[KYUUBI #939][FOLLOWUP][TEST] Add string column test for Z-Order

### PR DESCRIPTION
**Pull request by zhaomin1423**
### _Why are the changes needed?_

Added string column test for zorder.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
thank you @zhaomin1423 , can we also test the string column with null value ?

**Comment by ulysses-you** [comment]
also cc @cfmcgrady

**Comment by zhaomin1423** [comment]
> thank you @zhaomin1423 , can we also test the string column with null value ?

done

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merged to maset

**Pull request closed without merging**
