### PR TITLE
Use underscore instead hyphen in path

### PR DESCRIPTION
**Pull request by hddong**
### _Why are the changes needed?_

Use underscore instead hyphen in path, friendly to sql.

### _How was this patch tested?_
- [X] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master/branch-1.3

**Comment by ulysses-you** [comment]
hi @hddong there is some conflict in branch-1.3, can you send a new PR for that branch ?

**Comment by hddong** [comment]
@ulysses-you: Sure, I will do it in a while.

**Comment by hddong** [comment]
@ulysses-you: I confirmed, it is not need. The code is not in branch-1.3.

**Comment by ulysses-you** [comment]
@hddong  ah, I see. thank you for the confirm !

**Pull request closed without merging**
