### PR TITLE
Load dynamic jar

### PR DESCRIPTION
**Pull request by turboFei**
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
```
- scala code with loading external package at runtime  *** FAILED ***
  org.apache.kyuubi.shade.org.apache.hive.service.cli.HiveSQLException: Error operating EXECUTE_STATEMENT: org.apache.kyuubi.KyuubiSQLException: Failed to add jar file:/home/runner/work/incubator-kyuubi/incubator-kyuubi/integration-tests/kyuubi-kubernetes-it/target/tmp/kyuubi-5fb8a257-5433-4bbb-993f-70495575c7f6/test-function.jar
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3(ExecuteScala.scala:73)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3$adapted(ExecuteScala.scala:68)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$1(ExecuteScala.scala:68)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.kyuubi.engine.spark.operation.SparkOperation.withLocalProperties(SparkOperation.scala:88)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.runInternal(ExecuteScala.scala:60)
	at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:157)
	at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:94)
	at org.apache.kyuubi.engine.spark.session.SparkSessionImpl.runOperation(SparkSessionImpl.scala:65)
	at org.apache.kyuubi.session.AbstractSession.$anonfun$executeStatement$1(AbstractSession.scala:123)
	at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:75)
	at org.apache.kyuubi.session.AbstractSession.executeStatement(AbstractSession.scala:120)
	at org.apache.kyuubi.service.AbstractBackendService.executeStatement(AbstractBackendService.scala:66)
	at org.apache.kyuubi.service.TFrontendService.ExecuteStatement(TFrontendService.scala:233)
	at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1557)
	at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1542)
	at org.apache.kyuubi.shade.org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.kyuubi.shade.org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
	at org.apache.kyuubi.shade.org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at scala.tools.nsc.Global.assoc$1(Global.scala:885)
	at scala.tools.nsc.Global.$anonfun$invalidateClassPathEntries$2(Global.scala:900)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at scala.tools.nsc.Global.invalidateClassPathEntries(Global.scala:900)
	at scala.tools.nsc.Global.extendCompilerClassPath(Global.scala:835)
	at scala.tools.nsc.interpreter.IMain.addUrlsToClassPath(IMain.scala:254)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3(ExecuteScala.scala:70)
	... 25 more
  at org.apache.kyuubi.jdbc.hive.Utils.verifySuccess(Utils.java:270)
  at org.apache.kyuubi.jdbc.hive.Utils.verifySuccessWithInfo(Utils.java:256)
  at org.apache.kyuubi.jdbc.hive.KyuubiStatement.runAsyncOnServer(KyuubiStatement.java:316)
  at org.apache.kyuubi.jdbc.hive.KyuubiStatement.executeWithConfOverlay(KyuubiStatement.java:238)
  at org.apache.kyuubi.jdbc.hive.KyuubiStatement.execute(KyuubiStatement.java:233)
  at org.apache.kyuubi.operation.SparkQueryTests.$anonfun$$init$$76(SparkQueryTests.scala:640)
  at org.apache.kyuubi.operation.SparkQueryTests.$anonfun$$init$$76$adapted(SparkQueryTests.scala:619)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3(JDBCTestHelper.scala:60)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3$adapted(JDBCTestHelper.scala:60)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  ...
  Cause: java.lang.RuntimeException: org.apache.kyuubi.KyuubiSQLException:Error operating EXECUTE_STATEMENT: org.apache.kyuubi.KyuubiSQLException: Failed to add jar file:/home/runner/work/incubator-kyuubi/incubator-kyuubi/integration-tests/kyuubi-kubernetes-it/target/tmp/kyuubi-5fb8a257-5433-4bbb-993f-70495575c7f6/test-function.jar
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3(ExecuteScala.scala:73)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3$adapted(ExecuteScala.scala:68)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$1(ExecuteScala.scala:68)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.kyuubi.engine.spark.operation.SparkOperation.withLocalProperties(SparkOperation.scala:88)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.runInternal(ExecuteScala.scala:60)
	at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:157)
	at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:94)
	at org.apache.kyuubi.engine.spark.session.SparkSessionImpl.runOperation(SparkSessionImpl.scala:65)
	at org.apache.kyuubi.session.AbstractSession.$anonfun$executeStatement$1(AbstractSession.scala:123)
	at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:75)
	at org.apache.kyuubi.session.AbstractSession.executeStatement(AbstractSession.scala:120)
	at org.apache.kyuubi.service.AbstractBackendService.executeStatement(AbstractBackendService.scala:66)
	at org.apache.kyuubi.service.TFrontendService.ExecuteStatement(TFrontendService.scala:233)
	at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1557)
	at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1542)
	at org.apache.kyuubi.shade.org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.kyuubi.shade.org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
	at org.apache.kyuubi.shade.org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at scala.tools.nsc.Global.assoc$1(Global.scala:885)
	at scala.tools.nsc.Global.$anonfun$invalidateClassPathEntries$2(Global.scala:900)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at scala.tools.nsc.Global.invalidateClassPathEntries(Global.scala:900)
	at scala.tools.nsc.Global.extendCompilerClassPath(Global.scala:835)
	at scala.tools.nsc.interpreter.IMain.addUrlsToClassPath(IMain.scala:254)
	at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3(ExecuteScala.scala:70)
	... 25 more
  at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
  at org.apache.kyuubi.engine.spark.operation.SparkOperation$$anonfun$onError$1.applyOrElse(SparkOperation.scala:113)
  at org.apache.kyuubi.engine.spark.operation.SparkOperation$$anonfun$onError$1.applyOrElse(SparkOperation.scala:97)
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
  at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$1(ExecuteScala.scala:95)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.apache.kyuubi.engine.spark.operation.SparkOperation.withLocalProperties(SparkOperation.scala:88)
  at org.apache.kyuubi.engine.spark.operation.ExecuteScala.runInternal(ExecuteScala.scala:60)
  at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:157)
  at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:94)
  ...
  Cause: java.lang.RuntimeException: org.apache.kyuubi.KyuubiSQLException:Failed to add jar file:/home/runner/work/incubator-kyuubi/incubator-kyuubi/integration-tests/kyuubi-kubernetes-it/target/tmp/kyuubi-5fb8a257-5433-4bbb-993f-70495575c7f6/test-function.jar
  at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
  at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3(ExecuteScala.scala:73)
  at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$3$adapted(ExecuteScala.scala:68)
  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
  at org.apache.kyuubi.engine.spark.operation.ExecuteScala.$anonfun$runInternal$1(ExecuteScala.scala:68)
  ...
  Cause: java.lang.RuntimeException: java.lang.NullPointerException:null
  at scala.tools.nsc.Global.assoc$1(Global.scala:885)
  at scala.tools.nsc.Global.$anonfun$invalidateClassPathEntries$2(Global.scala:900)
  at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
  at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
  at scala.tools.nsc.Global.invalidateClassPathEntries(Global.scala:900)
  ...
Run completed in 2 minutes, 49 seconds.
Total number of tests run: 124
Suites: completed 5, aborted 0
Tests: succeeded 105, failed 19, canceled 4, ignored 0, pending
```

**Comment by cutiechi** [comment]
How to unload?

**Comment by turboFei** [comment]
> How to unload?

Now spark does not support to unload added jar.

User have to create a new spark engine.

**Comment by turboFei** [comment]
Close this one, because it is just a testing.

@cutiechi 

please follow this PR https://github.com/apache/incubator-kyuubi/pull/2475

**Pull request closed without merging**
