### PR TITLE
Fix flaky test BatchRestApiSuite - basic batch rest client with invalid user

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

image

Wait the connection closed after each test.
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
it the way to fix still flaky？

**Comment by turboFei** [comment]
checking for this, re-order to have a test first.

**Comment by turboFei** [comment]
```
Run starting. Expected test count is: 0
StatementSuite:
org.apache.kyuubi.engine.jdbc.doris.StatementSuite *** ABORTED ***
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.kyuubi.engine.jdbc.doris.StatementSuite
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
  at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  ...
  Cause: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"[https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.3\](https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.3/)": unknown: unable to scan Account Service Account row from query: dial tcp 10.1.42.147:5432: connect: connection refused"}
  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
  at java.lang.Thread.run(Thread.java:750)
```

**Comment by turboFei** [comment]
cc @yaooqinn

**Review by pan3793 — APPROVED** [review]

**Comment by turboFei** [comment]
thanks @yaooqinn @pan3793 , merging to master

**Comment by turboFei** [comment]
thanks, merged to master and branch-1.6

**Pull request closed without merging**
