### PR TITLE
[KYUUBI #703][FOLLOWUP][DEPS][TEST] Reduce hudi spark extraJars deps

### PR DESCRIPTION
**Pull request by simon824**
### _Why are the changes needed?_
Reduce hudi spark extraJars deps , it is unnecessary to submit all jars.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by timothy65535** [comment]
hi @simon824, you can `checkout -b` a new branch for new patch next time.

image

**Comment by simon824** [comment]
> hi @simon824, you can `checkout -b` a new branch for new patch next time.
> 
> image

 Sorry, it's a bad habit, i'll pay attention next time.

**Review by timothy65535 — APPROVED** [review]

**Comment by timothy65535** [comment]
Also, it's better open a issue, then fix. 😃

**Review by pan3793 — APPROVED** [review]
LGTM

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
