### PR TITLE
[KYUUBI #1806] Fix LaunchEngine may be closed multiple times

### LINKED ISSUE #1806: The LaunchEngine may be closed multiple times
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When a query run took more than `kyuubi.operation.idle.timeout` (3 hours), operation LaunchEngine will be closed multiple times.

1. LaunchEngine will be closed by SessionManager.TimeoutChecker for the first time when the time reaches `kyuubi.operation.idle.timeout` 3 hours
2. LaunchEngine will be closed for the second time when the Kyuubi server receives the request TCloseSessionReq

### Affects Version(s)

master

### Kyuubi Server Log Output

```logtalk
22/01/17 03:11:03 INFO operation.LaunchEngine: Processing etl's query[901dd0f0-917a-410c-9a1b-16bff14dee36]: INITIALIZED_STATE -> PENDING_STATE, statement: LAUNCH_ENGINE
22/01/17 03:11:03 INFO log.OperationLog: Creating operation log file /opt/kyuubi/work/server_operation_logs/2ff1515a-e59e-49c5-bdad-eb412d6dab27/901dd0f0-917a-410c-9a1b-16bff14dee36
22/01/17 03:11:03 INFO operation.LaunchEngine: Processing etl's query[901dd0f0-917a-410c-9a1b-16bff14dee36]: PENDING_STATE -> RUNNING_STATE, statement: LAUNCH_ENGINE
22/01/17 03:11:04 INFO operation.LaunchEngine: Processing etl's query[901dd0f0-917a-410c-9a1b-16bff14dee36]: RUNNING_STATE -> FINISHED_STATE, statement: LAUNCH_ENGINE, time taken: 0.024 seconds
22/01/17 06:12:39 WARN operation.KyuubiOperationManager: Operation OperationHandle [type=UNKNOWN_OPERATION, identifier: 901dd0f0-917a-410c-9a1b-16bff14dee36] is timed-out and will be closed
22/01/17 06:12:39 INFO operation.LaunchEngine: Processing etl's query[901dd0f0-917a-410c-9a1b-16bff14dee36]: FINISHED_STATE -> CLOSED_STATE, statement: LAUNCH_ENGINE
org.apache.kyuubi.KyuubiSQLException: Invalid OperationHandle [type=UNKNOWN_OPERATION, identifier: 901dd0f0-917a-410c-9a1b-16bff14dee36]
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.operation.OperationManager.removeOperation(OperationManager.scala:89)
	at org.apache.kyuubi.operation.OperationManager.closeOperation(OperationManager.scala:104)
	at org.apache.kyuubi.session.AbstractSession.$anonfun$closeOperation$1(AbstractSession.scala:182)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:76)
	at org.apache.kyuubi.session.AbstractSession.closeOperation(AbstractSession.scala:180)
	at org.apache.kyuubi.session.KyuubiSessionImpl.close(KyuubiSessionImpl.scala:129)
	at org.apache.kyuubi.session.SessionManager.closeSession(SessionManager.scala:93)
	at org.apache.kyuubi.service.AbstractBackendService.closeSession(AbstractBackendService.scala:49)
	at org.apache.kyuubi.server.KyuubiServer$$anon$1.org$apache$kyuubi$server$BackendServiceTimeMetric$$super$closeSession(KyuubiServer.scala:139)
	at org.apache.kyuubi.server.BackendServiceTimeMetric.$anonfun$closeSession$1(BackendServiceTimeMetric.scala:43)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.kyuubi.metrics.MetricsSystem$.timerTracing(MetricsSystem.scala:103)
	at org.apache.kyuubi.server.BackendServiceTimeMetric.closeSession(BackendServiceTimeMetric.scala:43)
	at org.apache.kyuubi.server.BackendServiceTimeMetric.closeSession$(BackendServiceTimeMetric.scala:41)
	at org.apache.kyuubi.server.KyuubiServer$$anon$1.closeSession(KyuubiServer.scala:139)
	at org.apache.kyuubi.service.ThriftBinaryFrontendService.CloseSession(ThriftBinaryFrontendService.scala:228)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$CloseSession.getResult(TCLIService.java:1397)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$CloseSession.getResult(TCLIService.java:1382)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingProcessor.process(HadoopThriftAuthBridgeServer.scala:162)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by cfmcgrady**
### _Why are the changes needed?_

close #1806

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
It seems we should not remove the `LaunchEngine` until session close.

Can we override the `isTimedOut` of `LaunchEngine` and mark it never timeout ?

**Comment by yaooqinn** [comment]
> It seems we should not remove the `LaunchEngine` until session close.

not true

**Comment by yaooqinn** [comment]
indeed, we don't need to add it into OperationManger as it's a member of the session.

**Review by yaooqinn — APPROVED** [review]

**Comment by turboFei** [comment]
> indeed, we don't need to add it into OperationManger as it's a member of the session.
because we need fetch the launch engine log in client side, so it seems that we have to add it into operationManager.

> do we call CloseOperation separately at the client-side now?
not.

**Comment by yaooqinn** [comment]
> > indeed, we don't need to add it into OperationManger as it's a member of the session.
> 
> because we need fetch the launch engine log in client side, so it seems that we have to add it into operationManager.
> 
> > do we call CloseOperation separately at the client-side now?
> 
> not now.

I see

**Pull request closed without merging**
