### PR TITLE
[GA] Remove spark-bundled binary distributions in GA release

### LINKED ISSUE #798: Make distribution with --spark-provided as default an only in release.yml of GA

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

close #798

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
BTW, the release is still invalid according to apache policy after this change

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
I see, there are still lots of works to do to meet apache policies. The biggest one I think is that apache cares about the source release but we only have binary release now.

**Comment by yaooqinn** [comment]
spark-*-bin-*.tgz rm this in license

**Comment by yaooqinn** [comment]
thanks, merged to master

**Pull request closed without merging**
