### PR TITLE
[TEST] Add Zookeeper 3.4/3.5/3.6/3.7 integration test

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

This PR proposes to add Testcontainers based Zookeeper 3.4/3.5/3.6/3.7 integration test, we need it to verify the compatibility if we upgrade Zookeeper client to the new version. See details in #1941

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
thanks for driving this. it will be great if the compatibility is not an issue for us to upgrade zk.

Using sql pipeline to verify this looks not that good to me, I recommand we do not go this way.

the sql tests are not built and suite for this

- not that complete, we can not ensure the zk apis are all called, e.g. lock hehavior, error handling, zk acls, and those between ctl module and embedded zk. etc.
- too heavy, it take much time for test for our own ci building, and too much resources from the entire ASF github account. Althougth the resources are free for us, we'd better make reasonable use of it.
- if we add more tests to the trait, might make it even worse.

If we can build it individually to test all the apis between the kyuubi-ha(client) module and kyuubi-zookeeper(server), it will be much specific, complete and.resouece-friendly, WDYT?

**Comment by pan3793** [comment]
> If we can build it individually to test all the apis between the kyuubi-ha(client) module and kyuubi-zookeeper(server), it will be much specific, complete and.resouece-friendly, WDYT?

Make sense, I will try in this direction.

**Comment by hddong** [comment]
> If we can build it individually to test all the apis between the kyuubi-ha(client) module and kyuubi-zookeeper(server), it will be much specific, complete and.resouece-friendly, WDYT?

**Comment by hddong** [comment]
Sorry for wrong close.  `test all the apis` seems more friendly. We can try it after #1989.

**Comment by pan3793** [comment]
cc @yaooqinn @hddong, it's ready for review now

**Review by cxzl25 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to master

**Pull request closed without merging**
