### PR TITLE
Bump Hudi from 0.12.0 to 0.13.0

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- Hudi 0.13.0 release note: https://hudi.apache.org/releases/release-0.13.0/

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Upgrading Hudi should re-evaluate all transitive deps

**Comment by bowenliang123** [comment]
Closing this PR. As potential breaking changes for requiring `primaryKey` prop in 0.13.0, the failed test logs:
cc @cxzl25 
```
SparkHudiOperationSuite:
- get columns type *** FAILED ***
  org.apache.kyuubi.jdbc.hive.KyuubiSQLException: org.apache.kyuubi.KyuubiSQLException: Error operating ExecuteStatement: java.lang.IllegalArgumentException: No `primaryKey` is specified.
	at org.apache.hudi.common.util.ValidationUtils.checkArgument(ValidationUtils.java:40)
	at org.apache.spark.sql.hudi.HoodieOptionConfig$.validateTable(HoodieOptionConfig.scala:199)
	at org.apache.spark.sql.catalyst.catalog.HoodieCatalogTable.parseSchemaAndConfigs(HoodieCatalogTable.scala:260)
	at org.apache.spark.sql.catalyst.catalog.HoodieCatalogTable.initHoodieTable(HoodieCatalogTable.scala:173)
```

**Comment by cxzl25** [comment]
> Upgrading Hudi should re-evaluate all transitive deps

Let's continue to split the hudi module test.

https://github.com/apache/kyuubi/pull/4260

**Comment by cxzl25** [comment]
> java.lang.IllegalArgumentException: No `primaryKey` is specified.

```sql
 options (
   primaryKey = 'XXX',
```


Mandatory Record Key Field
The configuration for setting the record key field, hoodie.datasource.write.recordkey.field, is now required to be set and has no default value. Previously, the default value is uuid.

https://hudi.apache.org/releases/release-0.13.0/#mandatory-record-key-field

**Pull request closed without merging**
